[CN-1127] Improve setup of security group and firewall rules for AKS, EKS, GKE
hazelcast/hazelcast-platform-operator pull request #1017
Opened 2024-02-13 17:36 UTC by cheels

## Description
In the e2e test (including AWS, EKS ,Azure, Istio), we are allowing all IP addresses (0.0.0.0/0) as the source of network security. So this PR fixed this.

2024-02-14 14:35 UTC, hasancelik requested changes

2024-02-14 19:09 UTC, cheels commented on .github/workflows/e2e-aks.yaml
> +      - name: Get GH Public IP
Removed

2024-02-20 09:28 UTC, semihbkgr requested changes
We are using the same VPC for each test run in GKE platform.
So, It would be better to delete the `firewall-rules` after the execution in GKE and Istio workflows.

2024-02-27 16:50 UTC, semihbkgr approved these changes
LGTM 👍.
I have one question. Do we really need to set firewall rules for resilience tests?

2024-02-27 18:17 UTC, cheels commented
> LGTM 👍. I have one question. Do we really need to set firewall rules for resilience tests?
You are right. Removed this part.

2024-02-27 18:18 UTC, merged