Add CP subsytem config for Hazelcast CR [CN-1149]
hazelcast/hazelcast-platform-operator pull request #1041
Opened 2024-02-26 09:32 UTC by SeriyBg

## User Impact

Add the possibility to configure CP Subsystem in the Hazelcast CR

2024-03-07 11:39 UTC, cagric0 requested changes

2024-03-07 11:39 UTC, cagric0 commented on api/v1alpha1/hazelcast_validation.go
> +			v.Invalid(Path("spec", "cpSubsystem", "memberCount"), cp.MemberCount, "can not be greater the clusterSize")
Shouldn't we use different error messages for different cases to distinguish the failure reason?

2024-03-07 11:39 UTC, cagric0 commented on api/v1alpha1/hazelcast_validation.go
> +		v.Required(Path("spec", "cpSubsystem", "pvc"), "PVC should be configured")
The point is if cp is enabled either cp.Pvc or persistence.Pvc must be configured?

2024-03-07 11:39 UTC, cagric0 commented on api/v1alpha1/hazelcast_validation.go
> +	}
Can `GroupSize` be less than `MemberCount`?

2024-03-07 11:39 UTC, cagric0 commented on api/v1alpha1/hazelcast_validation.go
> +func (v *hazelcastValidator) validateCPSubsystem(h *Hazelcast) {
We are missing the integration tests for these validations. Could you add them?

2024-03-07 11:44 UTC, SeriyBg commented on api/v1alpha1/hazelcast_validation.go
> +			v.Invalid(Path("spec", "cpSubsystem", "memberCount"), cp.MemberCount, "can not be greater the clusterSize")
But this is the same reason. The only thing is that the `ClusterSize` is not specified, then we use the default `3` member count

2024-03-07 15:30 UTC, SeriyBg commented on api/v1alpha1/hazelcast_validation.go
> +	}
Yes, it can be less but not greater than

2024-03-11 13:13 UTC, cagric0 approved these changes

2024-03-14 14:08 UTC, merged