[CN-1152]: add localConfig to persistence
hazelcast/hazelcast-platform-operator pull request #1043
Opened 2024-02-27 15:29 UTC by kutluhanmetin

## Description

Makes it possible to restore from a PVC using newly added `localConfig` field to `persistence` configuration.

## User Impact

Users will be able to configure `localConfig` field to restore from an existing PVC. In the following example backup is located at `base/backupdir/backup-1709045128548`. After this configuration applied it is moved to the default base directory of the Hazelcast Platform Operator `data/hot-restart`.

Example:

```
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  licenseKeySecretName: hazelcast-license-key
  persistence:
    pvc:
      accessModes: ["ReadWriteOnce"]
      requestStorage: 20Gi
    restore:
      localConfig:
        baseDir: "base"
        backupDir: "backup"
        backupFolder: "backup-1709045128548"

```

2024-02-27 15:33 UTC, kutluhanmetin commented on helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml
> +                  repository: docker.io/kutluhanhazelcast/platform-operator-agent
Will update this

2024-03-06 10:03 UTC, SeriyBg requested changes

2024-03-06 10:03 UTC, SeriyBg commented on api/v1alpha1/hazelcast_types.go
> +	// +kubebuilder:default:={repository: "docker.io/kutluhanhazelcast/platform-operator-agent", version: "0.1.25"}
Leftover?

2024-03-06 10:03 UTC, SeriyBg commented on api/v1alpha1/hazelcast_types.go
> +	LocalConfiguration *RestoreFromLocalConfiguration `json:"localConfig,omitempty"`
```suggestion
	// Configuration to restore from local backup
	// +optional
	LocalConfiguration *RestoreFromLocalConfiguration `json:"localConfig,omitempty"`
```

2024-03-06 10:03 UTC, SeriyBg commented on api/v1alpha1/hazelcast_types.go
> +	return p.IsRestoreEnabled() && p.Restore.LocalConfiguration.BackupDir != ""
Can't `p.Restore.LocalConfiguration` also be `nil`?
Also, since `BackupDir` is annotated with required, it would be better to put a validation that guarantees that it's never `""`

2024-03-06 10:03 UTC, SeriyBg commented on api/v1alpha1/hazelcast_types.go
> +	BackupFolder string `json:"backupFolder,omitempty"`
`// +required` and `omitempty` contradicts

2024-03-10 20:21 UTC, kutluhanmetin commented on api/v1alpha1/hazelcast_types.go
> +	// +kubebuilder:default:={repository: "docker.io/kutluhanhazelcast/platform-operator-agent", version: "0.1.25"}
Yes, will change it after releasing the agent.

2024-03-10 20:22 UTC, kutluhanmetin commented on api/v1alpha1/hazelcast_types.go
> +	BackupFolder string `json:"backupFolder,omitempty"`
https://github.com/hazelcast/hazelcast-platform-operator/pull/1043/commits/97e28f513158db380a6c176660d13cab024aee02

2024-03-10 20:22 UTC, kutluhanmetin commented on api/v1alpha1/hazelcast_types.go
> +	return p.IsRestoreEnabled() && p.Restore.LocalConfiguration.BackupDir != ""
https://github.com/hazelcast/hazelcast-platform-operator/pull/1043/commits/97e28f513158db380a6c176660d13cab024aee02

2024-03-10 20:22 UTC, kutluhanmetin commented on api/v1alpha1/hazelcast_types.go
> +	LocalConfiguration *RestoreFromLocalConfiguration `json:"localConfig,omitempty"`
https://github.com/hazelcast/hazelcast-platform-operator/pull/1043/commits/97e28f513158db380a6c176660d13cab024aee02

2024-03-15 08:00 UTC, SeriyBg requested changes

2024-03-15 08:00 UTC, SeriyBg commented on internal/controller/hazelcast/hazelcast_resources.go
> +	pvcList := &v1.PersistentVolumeClaimList{}
Do we really need to get the `PersistentVolumeClaimList`? It is already defined in the `STS` as a PVC template. I guess it's much easier to use that

2024-03-17 12:35 UTC, kutluhanmetin commented on internal/controller/hazelcast/hazelcast_resources.go
> +	pvcList := &v1.PersistentVolumeClaimList{}
I don't think so. Because PVC Template's name cannot be decided without knowing the existing PVC names. We are changing pvc name to `persistence`. However, before we used `hot-restart-persistence` in some versions. If there is no PVC with `persistence` prefix and there is PVC with `hot-restart-persistence` prefix, we also want to be able attach that PVC not to loose data because of upgrade.

2024-03-18 09:58 UTC, SeriyBg commented on internal/controller/hazelcast/hazelcast_resources.go
> +	pvcList := &v1.PersistentVolumeClaimList{}
But why does it matter? If the old PVC template wasn't equal to `persistence`, then we just don't need to change it. Getting the list of the PVCs and then checking the name is error-prone, as we don't check to which pod it is bound to, etc.

2024-03-20 09:10 UTC, SeriyBg requested changes

2024-03-20 09:10 UTC, SeriyBg commented on internal/controller/hazelcast/hazelcast_resources.go
> +func restoreLocalAgentContainer(h *hazelcastv1alpha1.Hazelcast, conf hazelcastv1alpha1.RestoreFromLocalConfiguration, destBaseDir, pvcName string) v1.Container {
Isn't the `pvcName` equal to the `conf.PVCNamePrefix`? It seems like you're passing through a lot of functions a value that you already have in the configuration

2024-03-20 09:18 UTC, kutluhanmetin commented on internal/controller/hazelcast/hazelcast_resources.go
> +func restoreLocalAgentContainer(h *hazelcastv1alpha1.Hazelcast, conf hazelcastv1alpha1.RestoreFromLocalConfiguration, destBaseDir, pvcName string) v1.Container {
If localConfig is configured, yes. But, there are also two other logics to decide PVC name:
- https://github.com/hazelcast/hazelcast-platform-operator/pull/1043/files#diff-baf7ec7ae114fbd3cd04c5a0494f61e31eea64d3ac66746bb6b15fd619772539R2035
- https://github.com/hazelcast/hazelcast-platform-operator/pull/1043/files#diff-baf7ec7ae114fbd3cd04c5a0494f61e31eea64d3ac66746bb6b15fd619772539R2052

2024-03-20 09:19 UTC, kutluhanmetin commented on test/e2e/backup_restore_test.go
> +			hotBackup := hazelcastconfig.HotBackup(hbLookupKey, hazelcast.Name, labels)
https://github.com/hazelcast/hazelcast-platform-operator/pull/1043/commits/060b057fa93d1d982679db26472f997db5b36841

2024-03-20 09:19 UTC, kutluhanmetin commented on api/v1alpha1/hazelcast_types.go
> +	// DeprecatedBaseDir is a depreciated. Deprecated: Use restore.localConfig to restore from a local backup.
https://github.com/hazelcast/hazelcast-platform-operator/pull/1043/commits/060b057fa93d1d982679db26472f997db5b36841

2024-03-20 09:19 UTC, kutluhanmetin commented on api/v1alpha1/hazelcast_validation.go
> +	if p.RestoreFromLocalBackup() && p.Restore.LocalConfiguration.BackupFolder == "" {
https://github.com/hazelcast/hazelcast-platform-operator/pull/1043/commits/060b057fa93d1d982679db26472f997db5b36841

2024-03-20 10:42 UTC, cagric0 approved these changes
LGTM! Except two comment related issue.

2024-03-20 10:42 UTC, cagric0 commented on api/v1alpha1/hazelcast_types.go
> +	HotRestartPersistence PVCNamePrefix = "hot-restart-persistence"
Shouldn't these comments be vice versa?

2024-03-20 10:42 UTC, cagric0 commented on config/crd/bases/hazelcast.com_hazelcasts.yaml
> +                    type: string
I wanted to comment here even though the change should be done in `hazelcast_types.go` since we can see the problem as a user. I would say the description is confusing me. 

I don't know what is `DeprecatedBaseDir`, we use it as field name in internal api. But user don't know it. Is it a thing in the description? 
Other confusing part is `Deprecated: Use`. We weren't using `baseDir` for restoring, so why do we suggest them to use `localConfig` in `baseDir` description.

2024-03-20 10:49 UTC, kutluhanmetin commented on config/crd/bases/hazelcast.com_hazelcasts.yaml
> +                    type: string
https://github.com/hazelcast/hazelcast-platform-operator/pull/1043/commits/94a939c85d4f3e4bb89d8a31056895c53ee096e4

2024-03-20 10:53 UTC, kutluhanmetin commented on config/crd/bases/hazelcast.com_hazelcasts.yaml
> +                    type: string
> I don't know what is DeprecatedBaseDir, we use it as field name in internal api. But user don't know it. Is it a thing in the description?

I renamed it as BaseDir which user already knows.

> Other confusing part is Deprecated: Use. We weren't using baseDir for restoring, so why do we suggest them to use localConfig in baseDir description.

If I don't know wrong, we were using baseDir to restore from backups. We were setting a backup directory as BaseDir so that it will restore from that. As far as I know, there was no usage of BaseDir in practice. My intention here is to explain, _if you were using for the restore purpose, we now have localConfig instead_.

2024-03-25 10:58 UTC, SeriyBg approved these changes
One nit. Other than that LGTM

2024-03-25 10:58 UTC, SeriyBg commented on api/v1alpha1/hazelcast_types.go
> +	// BaseDir is a deprecated. Use restore.localConfig to restore from a local backup.
```suggestion
	// BaseDir is deprecated. Use restore.localConfig to restore from a local backup.
```

2024-03-26 14:43 UTC, merged