[CN-281] Change Hazelcast Configuration from env variables to configmap
hazelcast/hazelcast-platform-operator pull request #105
Opened 2022-01-04 09:29 UTC by mtyazici

Changes:

- Changed configuration from env variables to configmap
- Added pod annotation for restarting pods after specific configuration changes.

2022-01-05 13:29 UTC, alparslanavci requested changes
Thanks for the PR, @mtyazici! Added a few comments. Especially, I didn't get the MC changes, maybe you can elaborate on them.

2022-01-05 13:33 UTC, mtyazici commented on controllers/managementcenter/managementcenter_controller.go
> +//+kubebuilder:rbac:groups="",resources=events;services;configmaps;serviceaccounts;pods,verbs=get;list;watch;create;update;patch;delete,namespace=system
We don't really need this but if we don't add this here, the Role resource for the operator gets duplicated roles. I can revert this if we don't mind duplicated roles.

2022-01-05 13:33 UTC, mtyazici commented on controllers/hazelcast/hazelcast_resources.go
> +func hazelcastConfigMapData(h *hazelcastv1alpha1.Hazelcast) map[string]string {
Sure, I will add it.

2022-01-05 13:33 UTC, mtyazici commented on controllers/hazelcast/hazelcast_resources.go
> +	yml, _ := yaml.Marshal(config.HazelcastWrapper{Hazelcast: cfg})
I agree but I wasn't sure how to handle them, do you have a suggestion?

2022-01-05 13:36 UTC, mtyazici commented on controllers/hazelcast/hazelcast_resources.go
> +		corev1.EnvVar{
You are right, I will update it.

2022-01-05 13:37 UTC, mtyazici commented on controllers/config/managementcenter.go
> +package config
I think we can remove them and if we add configmap for MC, we can create them later.

2022-01-05 13:37 UTC, alparslanavci commented on controllers/managementcenter/managementcenter_controller.go
> +//+kubebuilder:rbac:groups="",resources=events;services;configmaps;serviceaccounts;pods,verbs=get;list;watch;create;update;patch;delete,namespace=system
IMO, duplicated roles are ok, since we'll most likely need to have separate roles for Hazelcast and MC (and maybe for Turbine too). Also, any unnecessary role binding might be considered as unnecessary permissions. But your call, we can keep them simple for now.

2022-01-05 13:38 UTC, alparslanavci commented on controllers/config/managementcenter.go
> +package config
Yes, better to remove it for now. We can add them when it is needed.

2022-01-05 13:41 UTC, mtyazici commented on controllers/managementcenter/managementcenter_controller.go
> +//+kubebuilder:rbac:groups="",resources=events;services;configmaps;serviceaccounts;pods,verbs=get;list;watch;create;update;patch;delete,namespace=system
I removed the configmap from MC permissions.

2022-01-05 13:42 UTC, alparslanavci commented on controllers/hazelcast/hazelcast_resources.go
> +	yml, _ := yaml.Marshal(config.HazelcastWrapper{Hazelcast: cfg})
Maybe just return them if not `nil`? If there's any error, it will be a breaking one. So, it might be better to handle in reconcile.

2022-01-05 13:44 UTC, alparslanavci commented
They are the ones that we discussed in the comments. I got them now, nothing else is needed. 👍

2022-01-05 14:38 UTC, alparslanavci approved these changes
Thanks for the changes!

2022-01-06 11:25 UTC, hakanmemisoglu commented on controllers/hazelcast/hazelcast_resources.go
> +	ans[n.CurrentHazelcastConfigForcingRestartChecksum] = fmt.Sprint(crc32.ChecksumIEEE(cfgYaml))
Is there a particular reason for using CRC32?
I remember you have used FNV32 before.

2022-01-06 11:29 UTC, hakanmemisoglu commented on controllers/config/hazelcast.go
> +	Enabled                      *bool  `yaml:"enabled,omitempty"`
Why not just bool? I guess the result will be the same. Does it need a third possible value?

2022-01-06 11:31 UTC, hakanmemisoglu approved these changes
@mtyazici Looks good to me. I have just few questions.

2022-01-06 11:39 UTC, mtyazici commented on controllers/hazelcast/hazelcast_resources.go
> +	ans[n.CurrentHazelcastConfigForcingRestartChecksum] = fmt.Sprint(crc32.ChecksumIEEE(cfgYaml))
You are right, I now remember I used FNV32 before. When I was writing this feature I searched for fast non-cryptographic algorithm to get the checksum and I found `CRC32. However, we could very well use `FNV32` in this case if you prefer it.

2022-01-06 11:40 UTC, mtyazici commented on controllers/config/hazelcast.go
> +	Enabled                      *bool  `yaml:"enabled,omitempty"`
Yes, we need a third value because we are using omitempty, if the value of the boolean variable  is false Marshall function will not put that field into the created yaml string. This is something we want to prevent if we want to be explicit about the configuration we create for Hazelcast members.

2022-01-06 11:43 UTC, mtyazici commented on controllers/hazelcast/hazelcast_resources.go
> +	ans[n.CurrentHazelcastConfigForcingRestartChecksum] = fmt.Sprint(crc32.ChecksumIEEE(cfgYaml))
I can change it to FNV32 so that we are consistent with our usage of checksum algorithm.

2022-01-06 11:47 UTC, hakanmemisoglu commented on controllers/hazelcast/hazelcast_resources.go
> +	ans[n.CurrentHazelcastConfigForcingRestartChecksum] = fmt.Sprint(crc32.ChecksumIEEE(cfgYaml))
It is up to you. I don't think using two different hashing mechanism will create big problem.

2022-01-06 11:49 UTC, hakanmemisoglu commented on controllers/config/hazelcast.go
> +	Enabled                      *bool  `yaml:"enabled,omitempty"`
Then you can remove `omitempty`. I have only seen one usage of this field and it is not a dynamic input.

2022-01-06 12:53 UTC, merged