Fix WAN replication tests
hazelcast/hazelcast-platform-operator pull request #1070
Opened 2024-03-18 18:49 UTC by cheels

## Description

Temporary update Hazelcast version to 5.5.0-SNAPSHOT to fix the issue in WAN tests with happening with 5.4.0-SNAPSHOT

2024-03-19 09:12 UTC, hasancelik requested changes

2024-03-19 09:12 UTC, hasancelik commented on .github/workflows/e2e-platform-wan.yaml
> +          make test-e2e NAMESPACE=src-ns RELEASE_NAME=src-ns E2E_TEST_LABELS=platform_wan REPORT_SUFFIX=ee_01 WORKFLOW_ID=wan HZ_VERSION=5.5.0-SNAPSHOT
My understanding was after the thread is using 5.4-BETA-2, as I mentioned before, we should not use 5.x before the 5.11 release

2024-03-19 18:07 UTC, cheels commented on .github/workflows/e2e-platform-wan.yaml
> +          make test-e2e NAMESPACE=src-ns RELEASE_NAME=src-ns E2E_TEST_LABELS=platform_wan REPORT_SUFFIX=ee_01 WORKFLOW_ID=wan HZ_VERSION=5.5.0-SNAPSHOT
Updated to 5.4-BETA-2

2024-03-21 11:42 UTC, hasancelik approved these changes

2024-03-25 10:53 UTC, merged