Add Kubernetes provider info into platform struct
hazelcast/hazelcast-platform-operator pull request #108
Opened 2022-01-20 17:03 UTC by mtyazici

2022-01-21 06:39 UTC, hasancelik requested changes

2022-01-21 06:39 UTC, hasancelik commented on controllers/platform/platform.go
> +	AWS ProviderType = "AWS"
It should be `EKS`

2022-01-21 09:37 UTC, mtyazici commented on controllers/platform/platform.go
> +	AWS ProviderType = "AWS"
Fixed it, thanks

2022-01-21 13:58 UTC, hakanmemisoglu approved these changes
LGTM. Just a small comment...

2022-01-21 13:58 UTC, hakanmemisoglu commented on controllers/platform/platform.go
> -		return plt, err
I'd convert this to return `nil` and change the function signature.

2022-01-21 14:01 UTC, mtyazici commented on controllers/platform/platform.go
> -		return plt, err
I agree with returning nil but what do you mean by changing function signature? Do you mean returning pointers?

2022-01-21 14:24 UTC, mtyazici commented
@hakanmemisoglu and @hasancelik,

I am thinking of setting the platform struct only at the operator start up. The struct will be set and consequent `get`s only will return the field. However, this requires that if the platform information cannot be set at startup the operator will exit.

The only reason I did it this way is because the Kubernetes version could get updated and operator would not be aware of that. However, operator will be restarted when there is a Kubernetes version update. So getting the Platform information only at startup is enough. WDYT?

2022-01-24 08:42 UTC, hasancelik commented
@mtyazici 

Good approach 👍  The operator has to retrieve Platform(Kubernetes | OCP) information during start-up because we modify our resources according to this info. So exit scenario should not be a problem for us.

2022-01-24 13:55 UTC, hasancelik approved these changes

2022-01-24 14:10 UTC, merged