Addn support for User Code Namespaces [CN-1131]
hazelcast/hazelcast-platform-operator pull request #1091
Opened 2024-04-10 09:33 UTC by SeriyBg

## User Impact

Possibility to configure User Code Namespaces via UserCodeNamespace CR

2024-04-12 16:31 UTC, cheels commented on helm-charts/hazelcast-platform-operator/templates/webhook.yaml
> +        path: /validate-hazelcast-com-v1alpha1-topic
here should be /validate-hazelcast-com-v1alpha1-usercodenamespace

2024-04-15 08:58 UTC, kutluhanmetin commented on api/v1alpha1/usercodenamespace_webhook.go
> +	return admission.Warnings{}, nil
Just to be more consistent, we can add `ValidateUCNSpecDelete` method which returns nil or we can delete `ValidateUCNSpecUpdate` and `ValidateCreate` methods.

2024-04-15 10:18 UTC, kutluhanmetin commented on internal/controller/hazelcast/hazelcast_resources.go
> +	//
Shall we delete them if they are not necessary?

2024-04-15 11:25 UTC, kutluhanmetin commented on internal/hazelcast-client/usercodenamespace_service.go
> +	class ucnResourceType = iota + 3
do we need `class` and `jar`? They are unused.

2024-04-15 11:27 UTC, kutluhanmetin approved these changes

2024-04-15 14:09 UTC, hasancelik approved these changes

2024-04-25 11:38 UTC, kutluhanmetin commented on internal/controller/hazelcast/usercodenamespace_controller.go
> +			bs, err := rest.NewBundleService("https://"+host+":8443", mtlsClient)
Shall we move 8443 to a constant in constants.go?

2024-04-25 12:23 UTC, SeriyBg commented on internal/controller/hazelcast/usercodenamespace_controller.go
> +			bs, err := rest.NewBundleService("https://"+host+":8443", mtlsClient)
Make sense. We actually have a function for building `AgentUrl`, I have reused it here

2024-04-26 11:55 UTC, hasancelik requested changes

2024-04-26 11:55 UTC, hasancelik commented on internal/controller/hazelcast/map_controller.go
> +			defaultWanReplicationRefCodec(hz, m),
Why did you add this method now?

2024-04-26 11:55 UTC, hasancelik commented on test/e2e/usercodenamespace_test.go
> +var _ = Describe("Hazelcast User Code Deployment", Group("user_code_namespace"), func() {
```suggestion
var _ = Describe("Hazelcast User Code Namespace", Group("user_code_namespace"), func() {
```

2024-04-26 11:55 UTC, hasancelik commented on test/e2e/usercodenamespace_test.go
> +	It("verify added UCN added before the HZ cluster creation is successful", Tag(Kind|Any), func() {
Can we use Hazelcast CR with executor service instead of Map CR with an entry listener?

2024-04-29 09:06 UTC, SeriyBg commented on test/e2e/usercodenamespace_test.go
> +	It("verify added UCN added before the HZ cluster creation is successful", Tag(Kind|Any), func() {
It turns out we cannot, as checking the executor service requires Java client call, so it's not possible from our operator E2E tests

2024-04-29 12:11 UTC, SeriyBg commented on internal/controller/hazelcast/map_controller.go
> +			defaultWanReplicationRefCodec(hz, m),
I needed to update the coded, and the version includes this change as well

2024-04-29 12:13 UTC, SeriyBg commented on config/crd/bases/hazelcast.com_maps.yaml
> +              userCodeNamespace:
What do you mean here?

2024-04-29 13:42 UTC, semihbkgr commented on api/v1alpha1/hazelcast_types.go
> +	UserCodeNamespaces *UserCodeNamespacesConfig `json:"userCodeNamespaces,omitempty"`
nit: why is the name of this field plural?

2024-04-30 06:55 UTC, SeriyBg commented on api/v1alpha1/hazelcast_types.go
> +	UserCodeNamespaces *UserCodeNamespacesConfig `json:"userCodeNamespaces,omitempty"`
That's the name of the feature: https://docs.hazelcast.com/hazelcast/5.4/clusters/user-code-namespaces

2024-04-30 07:05 UTC, hasancelik commented on config/crd/bases/hazelcast.com_maps.yaml
> +              userCodeNamespace:
resolved here --> https://github.com/hazelcast/hazelcast-platform-operator/pull/1091#discussion_r1580651627

2024-04-30 07:05 UTC, hasancelik approved these changes

2024-04-30 07:12 UTC, merged