[CN-276] add HotBackup CR and implementation
hazelcast/hazelcast-platform-operator pull request #114
Opened 2022-01-31 09:30 UTC by SeriyBg

2022-02-01 09:49 UTC, SeriyBg commented
This PR is based on #112 so it's better to review it after it's merged to `main`

2022-02-14 14:36 UTC, hasancelik requested changes

2022-02-14 14:36 UTC, hasancelik commented on controllers/hazelcast/hot_backup_controller.go
> +		logger.Error(err, "Could not trigger Hot Backup: Hazelcast resource not found")
When I try to create HotBackup CR with a non-existing HZ CR name, the operator returned an error but it still tries to change the cluster state:
```
2022-02-14T17:03:46.179+0300    ERROR   controllers.HotBackup   Could not trigger Hot Backup: Hazelcast resource not found      {"hazelcast-hot-backup": "default/hot-backup", "error": "Hazelcast.hazelcast.com \"test\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
.....
2022-02-14T17:03:46.183+0300    ERROR   controllers.HotBackup   Error creating HotBackup. Could not change the cluster state to PASSIVE {"hazelcast-hot-backup": "default/hot-backup", "error": "Post \"http://..svc.cluster.local:5701/hazelcast/rest/management/cluster/changeState\": dial tcp: lookup ..svc.cluster.local: no such host"}
```

2022-02-14 14:36 UTC, hasancelik commented on api/v1alpha1/hazelcast_types.go
> +	HazelcastName string `json:"hazelcastName"`
@SeriyBg I am not sure but `hazelcastName` might be confusing for users. probably we will encounter this question multiple times --> Is it cluster-name? :) I do not have a strong candidate to replace, `resourceName` or `crName`might be better, I think. If the user is applying `HotBackup` CR, we can assume that he/she already understands the context.

2022-02-14 14:36 UTC, hasancelik commented on controllers/hazelcast/hazelcast_resources.go
> +	if h.Spec.ClusterName == "" {
👍

2022-02-14 14:44 UTC, SeriyBg commented on api/v1alpha1/hazelcast_types.go
> +	HazelcastName string `json:"hazelcastName"`
@hasancelik agreed, with one addition that I would keep the `hazelcast` word in it, like `hazelcatResourceName`

2022-02-14 14:53 UTC, hasancelik commented on api/v1alpha1/hazelcast_types.go
> +	HazelcastName string `json:"hazelcastName"`
`hazelcatResourceName` sounds good to me 👍

2022-02-14 15:25 UTC, SeriyBg commented on controllers/hazelcast/hot_backup_controller.go
> +		logger.Error(err, "Could not trigger Hot Backup: Hazelcast resource not found")
Oops, missing `return` statement

2022-02-15 06:39 UTC, mtyazici approved these changes
LGTM, only put one question.

2022-02-15 06:39 UTC, mtyazici commented on api/v1alpha1/hazelcast_types.go
> +// HotBackupStatus defines the observed state of HotBackup
Is there a reason why we did not create a new file for the HotBackup CR?

2022-02-15 07:09 UTC, hasancelik commented on api/v1alpha1/hazelcast_types.go
> +// HotBackupStatus defines the observed state of HotBackup
Separate `_types.go` for every CR is a good idea, I think 👍

2022-02-15 08:57 UTC, SeriyBg commented on api/v1alpha1/hazelcast_types.go
> +// HotBackupStatus defines the observed state of HotBackup
For no specific reason, I've decided to put it in the same file based on the other operators' code structure. But I will move it to the separate file

2022-02-15 09:05 UTC, mtyazici commented on controllers/hazelcast/hot_backup_controller.go
> +package hazelcast
I think this should also be split into `hotbackup` folder.

2022-02-15 09:09 UTC, SeriyBg commented on controllers/hazelcast/hot_backup_controller.go
> +package hazelcast
We can split it, but `hotbackup` CR is directly related to the `hazelcast` one. That's why I think it's better to keep it inside the `hazelcast` package. Wdyt?

2022-02-15 09:10 UTC, mtyazici commented on controllers/hazelcast/hot_backup_controller.go
> +	}
Can we also put a step for checking if the Hazelcast Custom Resource is in a ready state?

2022-02-15 09:13 UTC, mtyazici commented on controllers/hazelcast/hot_backup_controller.go
> +package hazelcast
I agree it is directly related but it is also a different CR and has a separate controller, to be honest I am not sure what is the best way to handle it.

2022-02-15 09:23 UTC, mtyazici commented on controllers/hazelcast/hot_backup_controller.go
> +package hazelcast
I am OK with the current status.

2022-02-15 10:21 UTC, hasancelik approved these changes

2022-02-15 10:22 UTC, merged