Added 5 phone home tests and workflow
hazelcast/hazelcast-platform-operator pull request #118
Opened 2022-02-03 11:28 UTC by cheels

2022-02-07 08:45 UTC, mtyazici requested changes

2022-02-07 08:45 UTC, mtyazici commented on test/ph/phone_home_test.go
> +				evaluateReadyMembers(h)
I am not sure if this check is enough for ensuring the phone home request is sent. Maybe you could check if the `hazelcast.com/last-successful-spec` annotation is present in the Hazelcast CR.

2022-02-07 08:45 UTC, mtyazici commented on test/ph/phone_home_test.go
> +				Expect(bigQueryTable.K8sVersion).Should(Equal("1.21"), "K8sVersion metric")
I don't think we should hard code the version of GKE if we are not explicitly giving it in the Kubernetes cluster creation step in Github action file.

2022-02-07 08:45 UTC, mtyazici commented on test/ph/phone_home_test.go
> +			Expect(bigQueryTable.K8sVersion).Should(Equal("1.21"), "K8sVersion metric")
Same as above

2022-02-07 08:45 UTC, mtyazici commented on test/ph/phone_home_test.go
> +	evaluateReadyMembers := func(h *hazelcastcomv1alpha1.Hazelcast) {
I see that we are not using `h` in the function, this is also the case for the E2E tests. Maybe we can fix both of them at some point

2022-02-07 08:45 UTC, mtyazici commented on test/ph/phone_home_test.go
> +	"cloud.google.com/go/bigquery"
Could you separate imports into three groups? You can check this comment for more info https://github.com/hazelcast/hazelcast-platform-operator/pull/113#issuecomment-1023004335

2022-02-07 08:45 UTC, mtyazici commented on test/ph/util.go
> +	"cloud.google.com/go/bigquery"
Same as above

2022-02-08 15:41 UTC, hasancelik commented on .github/workflows/nightly-ph-gke.yaml
> +      matrix:
If we are deploying only EE cluster, why do we have matrix?

2022-02-08 15:48 UTC, cheels commented on .github/workflows/nightly-ph-gke.yaml
> +      matrix:
Just for the future, when we decide to run it agains OS- it will take less changes? But ok, I'll change it and delete everything related to matrix and leave only EE

2022-02-08 21:06 UTC, cheels commented on test/ph/phone_home_test.go
> +				evaluateReadyMembers(h)
Fixed, added function into test

2022-02-08 21:07 UTC, cheels commented on test/ph/phone_home_test.go
> +	evaluateReadyMembers := func(h *hazelcastcomv1alpha1.Hazelcast) {
Fixed. Removed from e2e tests as well

2022-02-08 21:07 UTC, cheels commented on .github/workflows/nightly-ph-gke.yaml
> +      matrix:
Fixed

2022-02-08 21:09 UTC, cheels commented on test/ph/phone_home_test.go
> +				Expect(bigQueryTable.K8sVersion).Should(Equal("1.21"), "K8sVersion metric")
Agree!Thx, fixed

2022-02-08 21:09 UTC, cheels commented on test/ph/phone_home_test.go
> +			Expect(bigQueryTable.K8sVersion).Should(Equal("1.21"), "K8sVersion metric")
Fixed

2022-02-08 21:10 UTC, cheels commented on test/ph/phone_home_test.go
> +	"cloud.google.com/go/bigquery"
Fixed

2022-02-08 21:10 UTC, cheels commented on test/ph/util.go
> +	"cloud.google.com/go/bigquery"
Fixed

2022-02-09 06:43 UTC, hasancelik approved these changes

2022-02-09 09:19 UTC, mtyazici approved these changes

2022-02-09 09:19 UTC, merged