Removed redundant NS creation command
hazelcast/hazelcast-platform-operator pull request #1184
Opened 2024-06-25 08:55 UTC by cheels

## Description
Fix the "Error from server (AlreadyExists): namespaces "test-operator-os" already exists" since "eksctl create iamserviceaccount --namespace test-operator-os" command creates namespace if it doesn't exist.

https://eksctl.io/usage/iamserviceaccounts/#:~:text=If%20the%20namespace%20doesn%27t%20exist%20already%2C%20it%20will%20be%20created.

2024-06-25 13:30 UTC, hasancelik requested changes
Could you use `${NAMESPACE}` during`iam-service-account` creation?

https://github.com/hazelcast/hazelcast-platform-operator/blob/main/.github/workflows/e2e-eks.yaml#L68-L76

2024-06-26 13:30 UTC, cheels commented
> Could you use `${NAMESPACE}` during`iam-service-account` creation?
> 
> https://github.com/hazelcast/hazelcast-platform-operator/blob/main/.github/workflows/e2e-eks.yaml#L68-L76

This is not necessary because it's not matrix in this part of workflow but then we use matrix

2024-06-26 13:34 UTC, hasancelik approved these changes

2024-06-26 13:41 UTC, kutluhanmetin approved these changes

2024-06-26 15:34 UTC, merged