[CN-96] Support for scheduled backups
hazelcast/hazelcast-platform-operator pull request #124
Opened 2022-02-09 16:30 UTC by SeriyBg

2022-02-21 13:26 UTC, hasancelik requested changes

2022-02-23 11:24 UTC, hasancelik approved these changes
LGTM 👍 

@SeriyBg, you marked this comment as resolved(probably accidentally :) ):
https://github.com/hazelcast/hazelcast-platform-operator/pull/124#discussion_r810983000
Could you check?

2022-02-23 11:52 UTC, SeriyBg commented
> LGTM 👍
> 
> @SeriyBg, you marked this comment as resolved(probably accidentally :) ): [#124 (comment)](https://github.com/hazelcast/hazelcast-platform-operator/pull/124#discussion_r810983000) Could you check?

@hasancelik yeah, it was marked so after rebasing. Agree, will add this after commend.
About the cron schedule, I have put `* * * * *` as this is useful for testing since it will run every minute. Should I change it?

2022-02-23 12:58 UTC, hakanmemisoglu approved these changes
LGTM, just a small comment.

However, I would like to see two more features, maybe later on:
- Multiple schedules support instead of creating 2 HotBackup CRs
- Choice between UTC or local time zone

2022-02-23 12:58 UTC, hakanmemisoglu commented on controllers/hazelcast/hot_backup_controller.go
> +	"github.com/hazelcast/hazelcast-platform-operator/controllers/util"
`hazelcast-platform-operator` imports can be moved to 3rd import group

2022-02-23 19:43 UTC, merged