Implement External IP status field for HZ and MC
hazelcast/hazelcast-platform-operator pull request #127
Opened 2022-02-11 07:30 UTC by hakanmemisoglu

Adds status field `externalAddresses` to Hazelcast and ManagementCenter CRs.

The field will be showed in `kubectl get` output. 
External addresses will not be empty in case:
- Hazelcast is configured with ExposeExternally Discovery type LoadBalancer.
- ManagementCenter is configured with ExposeExternally LoadBalancer type.

2022-02-11 13:20 UTC, SeriyBg requested changes
Added of few not so critical comments

2022-02-11 13:20 UTC, SeriyBg commented on controllers/util/util.go
> +func GetLoadBalancerAddress(lb *corev1.LoadBalancerIngress) string {
Can this func be private?

2022-02-11 13:20 UTC, SeriyBg commented on controllers/util/util.go
> +func GetDiscoveryService(ctx context.Context, cli client.Client, cr Predefined) (*corev1.Service, error) {
Also this one

2022-02-11 13:20 UTC, SeriyBg commented on controllers/util/util.go
> +	externalAddrs := make([]string, 0, 4)
Is there a reason why the default capacity is 4? Maybe it's better to set it to `len(svc.Status.LoadBalancer.Ingress)`?

2022-02-11 14:01 UTC, hakanmemisoglu commented on controllers/util/util.go
> +	externalAddrs := make([]string, 0, 4)
I will update it to the maximum item possible. I was just trying to get a constant that will cover most of the cases.

2022-02-11 14:01 UTC, hakanmemisoglu commented on controllers/util/predefined.go
> +type Predefined interface {
Makes sense!

2022-02-11 14:55 UTC, SeriyBg approved these changes
LGTM

2022-02-14 06:34 UTC, mtyazici approved these changes
LGTM as well. I have one question, why didn't we also include the NodePort service's external IP addresses. We could get a node's IP address and show it.

2022-02-14 07:43 UTC, hakanmemisoglu commented
@mtyazici These are the conditions we agreed on before starting the task. I think we can add your idea as a next task but I don't think publicly exposing node ports is a common scenario.

2022-02-14 16:03 UTC, merged