[CN-315] Implement Turbine support
hazelcast/hazelcast-platform-operator pull request #135
Opened 2022-02-16 10:26 UTC by hakanmemisoglu

Implements Turbine support

* A webhook for automatic Turbine sidecar injection
* New Turbine CRD for passing sidecar injection settings

2022-03-10 14:24 UTC, hasancelik requested changes

2022-03-10 14:24 UTC, hasancelik commented on api/v1alpha1/turbine_types.go
> +	Image string `json:"image"`
I think image configuration should be aligned with HZ and MC:
```
...
  repository: 'hazelcast/turbine-sidecar'
  version: 'latest'
```

2022-03-10 14:24 UTC, hasancelik commented on api/v1alpha1/turbine_types.go
> +	Namespace string `json:"namespace"`
it should be optional?

2022-03-10 14:24 UTC, hasancelik commented on config/samples/_v1alpha1_turbine.yaml
> +      namespace: hazelcast
```suggestion
      namespace: default
```
or namespace should not be configured here then kubebuilder default value will be used.

2022-03-10 14:24 UTC, hasancelik commented on controllers/certificate/client.go
> +// The reason that this function is called is to trigger a pod update with a temporary
```suggestion
// The reason that this function is called is to trigger a pod update - without restarting the pod - with a temporary
```

2022-03-10 14:24 UTC, hasancelik commented on controllers/certificate/default.go
> +)
Why you didn't put these constants into [naming/constant](https://github.com/hazelcast/hazelcast-platform-operator/blob/main/controllers/naming/constants.go)?

2022-03-10 14:24 UTC, hasancelik commented on controllers/certificate/filter.go
> +}
Why do we need all these filters? For example, `Generic` might be enough to detect secret existence?

2022-03-10 14:39 UTC, hasancelik reviewed
Could you update Tiltfile to remove Turbine CRs?
https://github.com/hazelcast/hazelcast-platform-operator/blob/main/Tiltfile#L58

2022-03-11 07:31 UTC, mtyazici requested changes
Left some comments on Turbine spec values and indentation of kustomize files.

2022-03-11 07:31 UTC, mtyazici commented on api/v1alpha1/turbine_types.go
> +	Cluster *HazelcastRef `json:"cluster,omitempty"`
This should be a required field to force users define `Cluster.Name`. We could also remove the pointer since the object will never be empty.

```suggestion
	Cluster HazelcastRef `json:"cluster"`
```

2022-03-11 07:31 UTC, mtyazici commented on api/v1alpha1/turbine_types.go
> +	Hazelcast *HazelcastReference `json:"hazelcast,omitempty"`
This should be a required field to force users define `Hazelcast.Cluster.Name` We could also remove the pointer since the object will never be empty.
```suggestion
	Hazelcast HazelcastReference `json:"hazelcast"`
```

2022-03-11 07:31 UTC, mtyazici commented on api/v1alpha1/turbine_types.go
> +	Sidecar *SidecarConfiguration `json:"sidecar,omitempty"`
To fill the default values of `SideCar` field we should give default values to it. At least one default field will allow other default values to be filled by the API server. It would be best to give an empty object but kubebuilder does not support empty object default value.
```suggestion
	// +kubebuilder:default:={Name:  "turbine-sidecar"}
	Sidecar *SidecarConfiguration `json:"sidecar,omitempty"`
```

2022-03-11 07:31 UTC, mtyazici commented on api/v1alpha1/turbine_types.go
> +	ClusterAddress *string `json:"clusterAddress,omitempty"`
Do we want to allow empty cluster address?

2022-03-11 07:31 UTC, mtyazici commented on api/v1alpha1/turbine_types.go
> +	AppPortName *string `json:"portName,omitempty"`
Do we want to allow empty app port name?

2022-03-11 07:31 UTC, mtyazici commented on config/default/kustomization.yaml
> +  - ../rbac
Was the indentation change manual? When I ran it on my local, it reverted your changes to old one.

2022-03-11 07:31 UTC, mtyazici commented on config/rbac/kustomization.yaml
> +  - service_account.yaml
Same indentation question.

2022-03-11 07:31 UTC, mtyazici commented on config/webhook/kustomization.yaml
> +resources:
Same indentation question.

2022-03-11 07:49 UTC, hakanmemisoglu commented on controllers/certificate/filter.go
> +}
This filter and all related expression is required to watch **only** the required secret.

2022-03-11 08:16 UTC, mtyazici commented on api/v1alpha1/turbine_types.go
> +	AppPortName *string `json:"portName,omitempty"`
Alright :+1:

2022-03-15 08:35 UTC, hasancelik approved these changes
Thanks for the updates. LGTM 👍 Great work @hakanmemisoglu 👏

2022-03-15 09:14 UTC, mtyazici approved these changes
LGTM :+1: , just left trivial comments.

2022-03-15 09:14 UTC, mtyazici commented on test/e2e/config/turbine/turbine.go
> +								Image:           "hakanmemisoglu/ping:0.1.0",
Are we going to create the images under hazelcast?

2022-03-15 09:14 UTC, mtyazici commented on test/e2e/config/turbine/turbine.go
> +								Image:           "hakanmemisoglu/pong:0.1.0",
same question

2022-03-15 10:29 UTC, hakanmemisoglu commented
@mtyazici I will migrate the image later on.

2022-03-15 10:30 UTC, merged