Fix default CRD field values and comments
hazelcast/hazelcast-platform-operator pull request #149
Opened 2022-03-03 08:52 UTC by mtyazici

Changes:
- Add enum tags from string enum types
- Use pointers for struct fields*
- Add omitempty for fields we don't want to use default go values
- Add default spec value for MC and HZ CRs to allow empty spec
- Remove applyDefaultValues functions from MC and HZ CRs 

\* This is needed because when empty structs with `omitempty` tag gets marshaled into json they don't get omitted by put as `{}`. Which in turn, activates the default values for the struct which we don't want because the user has not provided any input for the struct. This was present for `Persistence` field in Hazelcast CR as well as other struct fields.

2022-03-04 09:59 UTC, hakanmemisoglu commented on controllers/naming/constants.go
> -	HazelcastRepo = "hazelcast/hazelcast"
Are these changes necessary? They have the same meaning as far as I know, and the older one is more concise.

2022-03-04 09:59 UTC, hakanmemisoglu approved these changes

2022-03-04 10:04 UTC, mtyazici commented on controllers/naming/constants.go
> -	HazelcastRepo = "hazelcast/hazelcast"
There was a discrepancy between kubebuilder default values and default values in `constants.go`. I just chose one of them. We could also use the older one, I don't have a preference.

2022-03-15 15:15 UTC, hasancelik requested changes

2022-03-15 15:15 UTC, hasancelik commented on controllers/naming/constants.go
>  	HazelcastVersion = "5.0.2"
All constants whose default values are configured by kubebuilder are redundant, I think. Changing the value of them does not mean anything because they are used by only tests files. Should we move them to test package? And how can we keep them in sync with kubebuilder values?

2022-03-15 15:15 UTC, hasancelik commented on controllers/hazelcast/hazelcast_resources_test.go
> -			name:   "Empty hazelcast repository",
I think keeping these tests still is a good idea. WDYT?

2022-03-15 15:15 UTC, hasancelik commented on controllers/managementcenter/managementcenter_resource_test.go
> -		{
same

2022-03-15 17:09 UTC, mtyazici commented on api/v1alpha1/hazelcast_types.go
> +	// +kubebuilder:validation:Minimum=1
Then, we need to make the clusterSize a pointer. I will change it

2022-03-17 09:27 UTC, mtyazici commented on controllers/naming/constants.go
>  	HazelcastVersion = "5.0.2"
We have integration tests that ensure that our kubebuilder default values and default values in go files are the same. If not, our tests will fail and we will fix the values.

2022-03-17 09:27 UTC, mtyazici commented on controllers/hazelcast/hazelcast_resources_test.go
> -			name:   "Empty hazelcast repository",
Also we still have integration tests doing a very similar job to this test.

2022-03-17 09:28 UTC, mtyazici commented on controllers/managementcenter/managementcenter_resource_test.go
> -		{
Answered above.

2022-03-17 10:52 UTC, hasancelik approved these changes

2022-03-17 18:42 UTC, merged