[CN-190] Hazelcast Members detailed status
hazelcast/hazelcast-platform-operator pull request #171
Opened 2022-03-30 09:44 UTC by SeriyBg

2022-03-30 09:47 UTC, dzeromski-hazelcast commented on test/e2e/hazelcast_controller_e2e_test.go
> +		FIt("should update HZ detailed member status", func() {
"Fit" should be "It"? :)

2022-03-30 09:48 UTC, dzeromski-hazelcast commented on go.mod
> +replace github.com/hazelcast/hazelcast-go-client v1.3.0 => github.com/yuce/hazelcast-go-client v1.3.0-preext3.0.20220324011025-02c0712e56c7
Should we use some private repo here?

2022-03-30 09:49 UTC, SeriyBg commented on go.mod
> +replace github.com/hazelcast/hazelcast-go-client v1.3.0 => github.com/yuce/hazelcast-go-client v1.3.0-preext3.0.20220324011025-02c0712e56c7
No. But for now, the changes that we are using aren't yet merged to the `hazelcast/hazelcast-go-client`. Thus the PR itself should be merged after the Go-client changes are released

2022-03-30 09:51 UTC, mtyazici commented on Makefile
>  build: generate fmt vet ## Build manager binary.
Could you also update build-tilt directive with the build tags?

2022-03-30 10:13 UTC, SeriyBg commented on test/e2e/hazelcast_controller_e2e_test.go
> +		FIt("should update HZ detailed member status", func() {
Yeap, good catch! Changed it

2022-03-30 10:14 UTC, SeriyBg commented on Makefile
>  build: generate fmt vet ## Build manager binary.
Done! Also change the tag's settings, as `hazelcastinternal` should not be configurable

2022-04-01 07:35 UTC, mtyazici approved these changes
LGTM, just left two comments

2022-04-01 07:35 UTC, mtyazici commented on controllers/hazelcast/hazelcast_status_controller.go
>  		}
When I tested the status, I saw that the member statuses don't get enriched until the first ticker comes at 1 min after. Maybe we could add the updateMemberStates function here like the following:

```suggestion
		}
		  c.updateMemberStates(context.Background())
```

2022-04-01 07:35 UTC, mtyazici commented on controllers/hazelcast/hazelcast_status_controller.go
> +func fetchTimedMemberState(ctx context.Context, client *hazelcast.Client, uuid hztypes.UUID) (string, error) {
Do you think we should move `fetchTimedMemberState` function and its related structs to a separate file? How should we continue when we add `addMapConfig` and other codecs?

2022-04-01 08:10 UTC, dzeromski-hazelcast approved these changes

2022-04-01 08:35 UTC, hasancelik requested changes

2022-04-01 08:35 UTC, hasancelik commented on controllers/hazelcast/hazelcast_status_controller.go
> +	c.Log.Info("Updating Hazelcast status", "CR", c.NamespacedName)
@SeriyBg Our status update logs are a little bit noisy due to ticker:

<img width="816" alt="Screen Shot 2022-03-31 at 16 42 59" src="https://user-images.githubusercontent.com/6005622/161226586-2693f65f-bcd8-42a8-b70c-34dd5794b8b2.png">

2022-04-01 13:11 UTC, SeriyBg commented on controllers/hazelcast/hazelcast_status_controller.go
> +func fetchTimedMemberState(ctx context.Context, client *hazelcast.Client, uuid hztypes.UUID) (string, error) {
I'm not sure we should. The codecs are in a separate package, but the `fetchTimedMemberState` is related to the `status`. So I would not mix `fetchTimedMemberState` and `addMapConfig` into the same file but rather separate it by the logic. WDYT?

2022-04-01 13:17 UTC, mtyazici commented on controllers/hazelcast/hazelcast_status_controller.go
> +func fetchTimedMemberState(ctx context.Context, client *hazelcast.Client, uuid hztypes.UUID) (string, error) {
I did not say we should mix them in the same file but in separate files. Maybe we will not need it as you say. Better to keep it like you did.

2022-04-01 14:53 UTC, hasancelik commented on controllers/hazelcast/hazelcast_status_controller.go
>  		}
I realized the same thing, is there any reason behind that? @SeriyBg

2022-04-01 15:16 UTC, hasancelik approved these changes

2022-04-01 15:19 UTC, mtyazici commented on controllers/hazelcast/hazelcast_status_controller.go
>  		}
Yes, its because we only enrich the memberData in updateMemberStates function and it is only called in the ticker goroutine.

2022-04-02 09:58 UTC, SeriyBg commented on controllers/hazelcast/hazelcast_status_controller.go
>  		}
Good catch, thanks @mtyazici! However, I've implemented it a bit differently, to enrich each member right after the new member event. With this, we will evitate the redundant call to already enriched members

2022-04-04 11:04 UTC, merged