[CN-306] Define restore agent config types
hazelcast/hazelcast-platform-operator pull request #196
Opened 2022-04-19 10:43 UTC by dzeromski-hazelcast

2022-04-20 11:16 UTC, cagric0 commented on api/v1alpha1/hazelcast_types.go
> +	AgentVersion string `json:"agentVersion,omitempty"`
Backup and Restore agents are the same agent. Why don't we use single _AgentRepository_ and _AgentVersion_?

2022-04-26 14:20 UTC, hasancelik requested changes

2022-04-26 14:20 UTC, hasancelik commented on api/v1alpha1/hazelcast_types.go
> +	Restore RestoreAgentConfiguration `json:"restore,omitempty"`
It should be pointer, see https://github.com/hazelcast/hazelcast-platform-operator/pull/195#discussion_r853264539 and 
https://github.com/hazelcast/hazelcast-platform-operator/blob/28c1d27efb9195b35533ba5dd8951cbb2660d934/api/v1alpha1/hazelcast_types.go#L79
After pointer change, IsEnabled() should be also updated, see https://github.com/hazelcast/hazelcast-platform-operator/blob/28c1d27efb9195b35533ba5dd8951cbb2660d934/api/v1alpha1/hazelcast_types.go#L304

2022-04-28 21:56 UTC, dzeromski-hazelcast commented on api/v1alpha1/hazelcast_types.go
> +	AgentVersion string `json:"agentVersion,omitempty"`
This is the requirement from TDD. I guess there could be a case where no backup is defined and only restore is.

2022-04-28 21:57 UTC, dzeromski-hazelcast commented on config/samples/_v1alpha1_hazelcast_persistence_restore.yaml
> +    agentRepository: dzeromskhazelcast/platform-operator-agent
Will need to update this before final commit. Right now we point to latest development agent.

2022-04-28 21:57 UTC, dzeromski-hazelcast commented on config/samples/_v1alpha1_hazelcast_persistence_restore.yaml
> +    bucketPath: "s3://hazelcast-cn-306-restore-tests?prefix=hazelcast/2022-02-21-14-23-52/&region=us-east-1"
Again, need to change it before final version. This is just an example.

2022-04-28 21:58 UTC, dzeromski-hazelcast commented on api/v1alpha1/hazelcast_types.go
> +	Restore RestoreAgentConfiguration `json:"restore,omitempty"`
Fixed

2022-04-29 08:26 UTC, hasancelik requested changes

2022-04-29 08:52 UTC, cagric0 approved these changes
LGTM!

2022-04-29 10:43 UTC, dzeromski-hazelcast commented on controllers/hazelcast/hazelcast_resources.go
> +				Name: "AWS_SESSION_TOKEN",
It was due to SSO requirement. Will delete this as in productions it wont be used. Good catch.

2022-05-11 10:00 UTC, cagric0 commented on api/v1alpha1/hazelcast_types.go
>  	BucketSecret string `json:"bucketSecret,omitempty"`
Same with restore. This also shouldn't be optional I think.

2022-05-11 10:14 UTC, dzeromski-hazelcast commented on api/v1alpha1/hazelcast_types.go
> +	BucketPath string `json:"bucketPath,omitempty"`
We can discuss this with @hasancelik.

2022-05-11 10:25 UTC, cagric0 commented on api/v1alpha1/hazelcast_types.go
> +	BucketPath string `json:"bucketPath,omitempty"`
We already talked actually but we can have a call together

2022-05-13 08:43 UTC, hasancelik requested changes

2022-05-13 08:43 UTC, hasancelik commented on api/v1alpha1/hazelcast_types.go
> +	BucketPath string `json:"bucketPath,omitempty"`
As @cagric0 mentioned, we talked about it, and making them non-optional is more reasonable for UX.

2022-05-13 09:20 UTC, dzeromski-hazelcast commented on api/v1alpha1/hazelcast_types.go
>  	BucketSecret string `json:"bucketSecret,omitempty"`
Fixed.

2022-05-13 09:20 UTC, dzeromski-hazelcast commented on api/v1alpha1/hazelcast_types.go
> +	BucketPath string `json:"bucketPath,omitempty"`
Fixed.

2022-05-13 09:45 UTC, hasancelik approved these changes

2022-05-13 09:46 UTC, SeriyBg commented on controllers/hazelcast/hazelcast_resources.go
> +	state, err := rest.GetState(ctx)
Just wondering, could we just check the `h.Status.Members` instead of making the REST call?

2022-05-13 09:46 UTC, SeriyBg commented on controllers/hazelcast/hazelcast_resources.go
> +	if state != "passive" {
What if the state is `frozen` or any other state apart from `passive`? Is this the acceptable scenario for us?

2022-05-13 09:55 UTC, SeriyBg commented on controllers/hazelcast/hazelcast_resources.go
> +		if ClusterState(member.State) != Passive {
To add to this. In the `TimedMemberState` we have a field `"clusterState": "ACTIVE"`. Maybe we could just add the `clusterState` to the `HazelcastStatus` and update in the `updateMembers` func in the `hazelcast_status_controller`? This will simplify this whole method

2022-05-13 10:49 UTC, dzeromski-hazelcast commented on controllers/hazelcast/hazelcast_resources.go
> +		if ClusterState(member.State) != Passive {
We could but this is new to me. Can we do the simplification and adding new state property in a new PR?

2022-05-13 10:50 UTC, dzeromski-hazelcast commented on controllers/hazelcast/hazelcast_resources.go
> +	state, err := rest.GetState(ctx)
We are checking members state few lines before. This rest call is just to avoid stale state before we try to activate.

2022-05-13 10:51 UTC, dzeromski-hazelcast commented on controllers/hazelcast/hazelcast_resources.go
> +	if state != "passive" {
This is undefined for our case so we ignore it. Proper restore will always start nodes in passive state, cluster in passive state with restore status set and pending phase. If anything differs it basically failed restore for us and we do nothing then.

2022-05-16 14:48 UTC, merged