[CN-370] Persist Map Configs into Hazelcast Configmap
hazelcast/hazelcast-platform-operator pull request #204
Opened 2022-04-28 08:09 UTC by mtyazici

TODO: 
- [] I will delete the file `controllers/protocol/types/enums.go`. Right now it contains all the commented out enums, I am not sure how, but I think we should keep these enums documented in the code.

2022-05-10 14:40 UTC, hasancelik commented on test/e2e/hazelcast_controller_e2e_test.go
> +			// TODO: Hazelcast side returns these bitmapIndexOptions even though we give them empty.
leftover?

2022-05-11 07:06 UTC, mtyazici commented on test/e2e/hazelcast_controller_e2e_test.go
> +			// TODO: Hazelcast side returns these bitmapIndexOptions even though we give them empty.
I am not sure if this is a problem from Hazelcast side or is intended. If it is intended we can delete the comment, otherwise we shouls keep it to change it in the future.

2022-05-11 08:41 UTC, mtyazici commented on controllers/hazelcast/map_controller.go
> +		if !reflect.DeepEqual(mcfg, currentMcfg) { // TODO replace DeepEqual with custom implementation
If it does not affect the performance, we can keep using reflection.

2022-05-13 08:07 UTC, hasancelik requested changes

2022-05-13 08:07 UTC, hasancelik commented on controllers/protocol/types/enums.go
> +// type IndexType int32
I think we can remove this file directly

2022-05-13 08:27 UTC, mtyazici commented on controllers/protocol/types/enums.go
> +// type IndexType int32
I will remove it then

2022-05-13 08:40 UTC, hasancelik approved these changes

2022-05-13 09:27 UTC, SeriyBg approved these changes

2022-05-13 10:08 UTC, cagric0 approved these changes

2022-05-13 12:02 UTC, merged