[CN-368] WAN Replication
hazelcast/hazelcast-platform-operator pull request #226
Opened 2022-05-30 07:03 UTC by hakanmemisoglu

Implement WAN Replication CR and reconciler

TODO:
- E2E Tests: 
   - Send data to another cluster and check them with the client
   - Check delete and update events are replicated to the target cluster
   - Send data to target A, then update WAN config to target B cluster

2022-06-21 14:08 UTC, mtyazici requested changes
Thanks for the PR. There are some things I mentioned in the comments otherwise LGTM.

2022-06-21 14:08 UTC, mtyazici commented on controllers/hazelcast/wanconfiguration_controller.go
> +	if !isSuccessfullyApplied(wan) {
Do we need this check?

2022-06-22 08:27 UTC, hakanmemisoglu commented on controllers/hazelcast/wanconfiguration_controller.go
> +	cli, err := r.getHazelcastClient(ctx, wan)
It is used in the else block.

2022-06-22 08:44 UTC, mtyazici commented on controllers/hazelcast/wanconfiguration_controller.go
> +			return updateWanStatus(ctx, r.Client, wan, wanPendingStatus())
Then how is the reconcile function triggered again because we are returning from the function with no errors?

2022-06-22 08:45 UTC, hakanmemisoglu commented on controllers/hazelcast/wanconfiguration_controller.go
> +			return updateWanStatus(ctx, r.Client, wan, wanPendingStatus())
Because of the update?

2022-06-22 08:47 UTC, mtyazici commented on controllers/hazelcast/wanconfiguration_controller.go
> +			return updateWanStatus(ctx, r.Client, wan, wanPendingStatus())
Ah, yes you are right :D

2022-06-27 08:10 UTC, mtyazici approved these changes
LGTM :+1:  Just left a few comments.

2022-06-27 08:23 UTC, hakanmemisoglu commented on controllers/hazelcast/wanconfiguration_controller.go
> +	updated, err := hasUpdate(wan)
Yes, updating is not supported right now.

2022-06-27 10:39 UTC, hasancelik commented on Tiltfile
>  cmd_button('Delete CRs and PVCs',
I think we need to wait/sleep between wanreplication and map CR removal processes. Otherwise, we will get the error below at tilt dashboard:
```
ERROR	controller-runtime.manager.controller.wanconfiguration	Reconciler error	{"reconciler group": "hazelcast.com", "reconciler kind": "WanConfiguration", "name": "wan", "namespace": "default", "error": "failed to get Map CR from WanConfiguration: Map.hazelcast.com \"map-wan\" not found"}
```

2022-06-27 10:40 UTC, hasancelik approved these changes
Thanks for the PR 👏 

LGTM 👍 with minor comment

2022-06-27 10:49 UTC, mtyazici commented
Ah, also another comment I forgot to make. When we delete the map CR before the WanReplication, WanReplication CR does not get deleted because the operator cannot delete the finalizer.

2022-06-27 10:51 UTC, hakanmemisoglu commented
Yes, that's correct. We need to add a finalizer to Map CR, or WAN reconciler needs to store the necessary information in WAN Status. We should discuss it in more detail.

2022-06-28 09:51 UTC, SeriyBg approved these changes
Left a few nitpicking comments 😃 . LGTM

2022-06-28 10:08 UTC, hakanmemisoglu commented on config/samples/_v1alpha1_wanreplication.yaml
> +  mapResourceName: map
Yes, we only support one map for each WanReplication. The user needs to create multiple WanReplication for multiple Map. We can change it if the need arises.

2022-06-28 10:08 UTC, hakanmemisoglu commented on controllers/hazelcast/wanreplication_controller.go
> +	if wan.GetDeletionTimestamp().IsZero() {
I directly got it from the reference book. Let me check it and update if they are same.

2022-06-29 07:06 UTC, merged