[CN 444] Add Executor Service e2e test
hazelcast/hazelcast-platform-operator pull request #311
Opened 2022-08-08 10:54 UTC by cagric0

2022-08-11 11:26 UTC, SeriyBg requested changes

2022-08-11 11:26 UTC, SeriyBg commented on bundle.yaml
> +          value: "true"
Leftover?

2022-08-11 11:26 UTC, SeriyBg commented on config/manager/kustomization.yaml
> +    kind: Deployment
Same here?

2022-08-11 11:26 UTC, SeriyBg commented on controllers/hazelcast/hazelcast_resources.go
> +	fillHazelcastConfigWithExecutorServices(&cfg, h)
Why is this method called twice?

2022-08-11 11:26 UTC, SeriyBg commented on test/e2e/helpers_test.go
> +func assertBasicES(bes1 hazelcastcomv1alpha1.ExecutorServiceConfiguration, bes2 codecTypes.ExecutorServiceConfig) {
I would suggest renaming the parameters to something like `expected` and `actual`, as the `1/2` suffix makes it kinda confusing

2022-08-11 11:52 UTC, cagric0 commented on bundle.yaml
> +          value: "true"
Yes, thank you!

2022-08-12 08:10 UTC, dzeromski-hazelcast approved these changes

2022-08-12 08:12 UTC, SeriyBg approved these changes
Approved with small nits 😄

2022-08-12 08:12 UTC, SeriyBg commented on test/e2e/hazelcast_user_code_test.go
> +			Expect(err).To(BeNil())
Small nit
```suggestion
			Expect(cl.Shutdown(context.Background())).Should(Succeed())
```

2022-08-12 08:12 UTC, SeriyBg commented on test/e2e/hazelcast_user_code_test.go
> +			Expect(err).To(BeNil())
```suggestion
			Expect(cl.Shutdown(context.Background())).Should(Succeed())
```

2022-08-12 10:14 UTC, merged