[CN-411] Expose inMemoryFormat in Map CR and properties in HZ CR
hazelcast/hazelcast-platform-operator pull request #334
Opened 2022-08-18 14:27 UTC by cagric0

2022-08-19 07:06 UTC, SeriyBg commented on api/v1alpha1/hazelcast_types.go
> +	Properties map[string]string `json:"properties,omitempty"`
As far as I understand, with the `Properties` we are exposing the raw Hazelcast configs to the user. Do we really want to do so?

2022-08-22 07:54 UTC, cagric0 commented on api/v1alpha1/hazelcast_types.go
> +	Properties map[string]string `json:"properties,omitempty"`
Yes, you are right about your concern but we already talked about it with Hasan. We need to expose some of the properties. As you can see in validation.go, we have blacklist of properties and we are filtering the properties according to that blacklist. For now the blacklist is empty, but later we are gonna add some properties to that list to prevent them to be exposed.

2022-08-22 09:07 UTC, mtyazici requested changes
Thanks for the PR! Could you also update the `createMapConfig` function in `hazelcast_resources.go` to reflect the changes done to `InMemoryFormat`.

2022-08-22 09:07 UTC, mtyazici commented on test/integration/hazelcast_controller_test.go
> +		FIt("should pass the values to ConfigMap", Label("fast"), func() {
Forgotten focused test

2022-08-23 08:34 UTC, mtyazici approved these changes
LGTM :+1:

2022-08-23 08:41 UTC, SeriyBg approved these changes

2022-08-23 09:29 UTC, merged