[CN-539] Add MultiMap CR
hazelcast/hazelcast-platform-operator pull request #367
Opened 2022-09-23 09:29 UTC by cagric0

New CR created and auto generated files are added.
Phonehome data and sample yaml are added.
[addMultiMapConfig](https://github.com/hazelcast/hazelcast-client-protocol/blob/master/protocol-definitions/DynamicConfig.yaml#L5) codec is added 
Controller, and integration-e2e tests are implemented.

2022-09-23 10:51 UTC, mtyazici commented on controllers/hazelcast/multimap_controller.go
> +	h := &hazelcastv1alpha1.Hazelcast{}
Can we make this a function? AFAIR, we are using the same code block in the map reconciler.

2022-09-30 10:50 UTC, hasancelik requested changes
Can we add multimap removal logic into the Hazelcast CR finalizer [as we did for Map CR before](https://github.com/hazelcast/hazelcast-platform-operator/pull/314)?

2022-09-30 10:53 UTC, cagric0 commented on config/crd/bases/hazelcast.com_multimaps.yaml
> +    singular: multimap
Nice. I was searching where to define shortname :)

2022-09-30 11:16 UTC, mtyazici commented on config/crd/bases/hazelcast.com_multimaps.yaml
> +    singular: multimap
You can do it in the code with, kubebuilder comments. There is an example at `CronHotBackup` CR.

2022-10-04 18:55 UTC, dzeromski-hazelcast approved these changes

2022-10-11 06:46 UTC, hasancelik approved these changes

2022-10-11 07:18 UTC, merged