[CN-583] Add Cache CR
hazelcast/hazelcast-platform-operator pull request #430
Opened 2022-11-08 11:24 UTC by SeriyBg

Add Cache CR

2022-11-21 11:13 UTC, cagric0 requested changes
Thanks for additional refactoring, I've left a few comment. Other than that LGTM!

2022-11-21 11:13 UTC, cagric0 commented on controllers/hazelcast/cache_controller.go
> +}
Just a reminder, after [Refactor HZ client PR](https://github.com/hazelcast/hazelcast-platform-operator/pull/425) is merged, we should update _CacheReconciler_ by adding _ClientRegistry_.

2022-11-21 11:13 UTC, cagric0 commented on controllers/hazelcast/multimap_controller.go
>  	multiMapInput.CollectionType = string(mms.CollectionType)
I think, _AsyncBackupCount_ field should be added to [fillAddMapConfigInput](https://github.com/hazelcast/hazelcast-platform-operator/blob/CN-583-cache-cr/controllers/hazelcast/map_controller.go#L298) same as here

2022-11-28 11:21 UTC, dzeromski-hazelcast approved these changes

2022-11-28 11:21 UTC, dzeromski-hazelcast commented on api/v1alpha1/cache_types.go
> +// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.state",description="Current state of the Queue Config"
Should it be queue or cache in the description?

2022-11-28 13:15 UTC, cagric0 approved these changes

2022-11-28 13:20 UTC, merged