[CN-621] Kind based E2E slow tests with Istio
hazelcast/hazelcast-platform-operator pull request #478
Opened 2022-11-29 11:51 UTC by semihbkgr

## Description

## User Impact

2022-12-02 12:32 UTC, semihbkgr commented on .github/workflows/istio-e2e-kind.yaml
> +          make test-e2e GO_TEST_FLAGS=${GO_TEST_FLAGS} NAMESPACE=$NAMESPACE NAME_PREFIX=$NAME_PREFIX WORKFLOW_ID=istio E2E_TEST_LABELS='&& !hz_expose_externally'
Yes, `hz_expose_externally` is intentionally disabled, because current implementation is not supporting exposeExternally with Istio.

2022-12-02 12:41 UTC, semihbkgr commented on .github/workflows/istio-e2e-kind.yaml
> +#  workflow_dispatch:
I forgot to remove it.

2022-12-02 12:55 UTC, cheels requested changes
This is only one small issue in yaml should be fixed and then this is good to go...

2022-12-02 12:55 UTC, cheels commented on .github/workflows/istio-e2e-kind.yaml
> +      - cron: "0 0 */3 * *"
```suggestion
  workflow_dispatch:
  schedule:
      - cron: "0 0 */3 * *"
```

2022-12-02 12:58 UTC, cheels commented on .github/workflows/istio-e2e-kind.yaml
> +      - cron: "0 0 */3 * *"
Also, why was chosen different from another workflow? Why it's not `- cron: "0 9 * * *"`

2022-12-02 13:11 UTC, semihbkgr commented on .github/workflows/istio-e2e-kind.yaml
> +      - cron: "0 0 */3 * *"
As far as I know, this workflow should run once in three days.

2022-12-02 13:20 UTC, cheels commented on .github/workflows/istio-e2e-kind.yaml
> +      - cron: "0 0 */3 * *"
I see, so  since it's a UTC, then it's better to use the same time as we use for Backup Workflow ("0 9 */3 * *")
It will run not at night but at the same time as other jobs but once in three days.

2022-12-02 15:23 UTC, cheels approved these changes

2022-12-13 11:40 UTC, semihbkgr commented
I add `E2E_TEST_EXCLUDED_SUITE` flag in makefile. It let you exclude explicit test suites easily in e2e tests

2022-12-22 10:23 UTC, cheels approved these changes

2022-12-22 10:29 UTC, mtyazici commented on Makefile
> +E2E_TEST_EXCLUDED_SUITE =
Does this not override what you give to the Makefile?

2022-12-22 10:31 UTC, semihbkgr commented on Makefile
> +E2E_TEST_EXCLUDED_SUITE =
What you mean?

2022-12-22 10:38 UTC, mtyazici commented on Makefile
> +E2E_TEST_EXCLUDED_SUITE =
It does not override it now I tested it :+1:

2023-01-31 06:28 UTC, mtyazici approved these changes

2023-02-03 09:51 UTC, cheels commented on .github/workflows/istio-e2e-gke.yaml
> +  get-image:
@semihbkgr Can you please change the step of getting the image? On the same way like it was done for GKE for example:
https://github.com/hazelcast/hazelcast-platform-operator/blob/main/.github/workflows/e2e-gke.yaml#L52-L90

And don't forget to use this everywhere where it needed https://github.com/hazelcast/hazelcast-platform-operator/blob/main/.github/workflows/e2e-gke.yaml#L104

2023-02-03 09:54 UTC, cheels commented on .github/workflows/istio-e2e-gke.yaml
> +  get-image:
@semihbkgr Can you please change the step of getting the image on the same way as it was done for GKE, for example:
https://github.com/hazelcast/hazelcast-platform-operator/blob/main/.github/workflows/e2e-gke.yaml#L52-L90

And don't forget to use this everywhere where it is needed https://github.com/hazelcast/hazelcast-platform-operator/blob/main/.github/workflows/e2e-gke.yaml#L104

2023-02-03 09:55 UTC, cheels requested changes
Please update get_image step on the latest way

2023-02-03 12:34 UTC, cheels approved these changes

2023-02-03 13:05 UTC, merged