Replace AutoForceStart with StartupAction [CN-623]
hazelcast/hazelcast-platform-operator pull request #511
Opened 2022-12-20 16:33 UTC by SeriyBg

## User Impact

Replace the `autoForceStart` option with the `startupAction` that allows the user to trigger `Force Start` or `Partial Start` when applied

2022-12-21 10:55 UTC, kutluhanmetin reviewed
When HZ License Key is specified and Community Image is used it still tries to operate

2022-12-21 12:37 UTC, SeriyBg commented
> When HZ License Key is specified and Community Image is used it still tries to operate

@kutluhanmetin good catch, thank you! Fixed

2022-12-21 12:40 UTC, kutluhanmetin approved these changes
LGTM

2022-12-23 08:22 UTC, hasancelik requested changes

2022-12-23 08:22 UTC, hasancelik commented on controllers/hazelcast/hazelcast_resources.go
> +func (r *HazelcastReconciler) persistenceStartupAction(ctx context.Context, h *hazelcastv1alpha1.Hazelcast, logger logr.Logger) error {
What if the user configures `startupAction` at first time cluster creation? I have tried and failed with error below:

```
    ....
    clusterDataRecoveryPolicy: "FullRecoveryOnly"
    startupAction: "ForceStart"
```

```
1.6717835618549035e+09	ERROR	controllers.Hazelcast	Cluster HotRestart did not finish successfully	{"hazelcast": "default/hazelcast", "error": "Post \"[http://hazelcast.default.svc.cluster.local:5701/hazelcast/rest/management/cluster/forceStart\":](http://hazelcast.default.svc.cluster.local:5701/hazelcast/rest/management/cluster/forceStart/%22:) dial tcp: lookup hazelcast.default.svc.cluster.local on 10.168.0.10:53: no such host"}
github.com/hazelcast/hazelcast-platform-operator/controllers/hazelcast.(*HazelcastReconciler).Reconcile
	/Users/hasancelik/GolandProjects/hazelcast-platform-operator/controllers/hazelcast/hazelcast_controller.go:190
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/Users/hasancelik/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/Users/hasancelik/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/hasancelik/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/Users/hasancelik/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234
1.6717835618940358e+09	INFO	controllers.Hazelcast	Persistence enabled with startup action.	{"hazelcast": "default/hazelcast", "action": "ForceStart"}
1.671783561916623e+09	ERROR	controllers.Hazelcast	Cluster HotRestart did not finish successfully	{"hazelcast": "default/hazelcast", "error": "Post
```

2022-12-23 15:38 UTC, SeriyBg commented on controllers/hazelcast/hazelcast_resources.go
> +func (r *HazelcastReconciler) persistenceStartupAction(ctx context.Context, h *hazelcastv1alpha1.Hazelcast, logger logr.Logger) error {
It is not related to the first start, as the ForceStart endpoint will be a no-op if there is not persistence folder. However, it is related to making the call when the pod is not ready yet. IMO, this error could just be logged as a `WARN`, since this is an expected behavior. WDYT?

2022-12-27 13:47 UTC, hasancelik commented on controllers/hazelcast/hazelcast_resources.go
> +func (r *HazelcastReconciler) persistenceStartupAction(ctx context.Context, h *hazelcastv1alpha1.Hazelcast, logger logr.Logger) error {
Logged as a WARN is ok but still, why do we allow users to do that? We can easily prevent it via validation webhook, right?

2022-12-28 08:49 UTC, SeriyBg commented on controllers/hazelcast/hazelcast_resources.go
> +func (r *HazelcastReconciler) persistenceStartupAction(ctx context.Context, h *hazelcastv1alpha1.Hazelcast, logger logr.Logger) error {
We can validate only for the `restore` option enabled, but one might need to trigger the `FORCE_START` action when just the persistence is enabled, without the restore option. We should not restrict this scenario, and we cannot validate it as well

2022-12-28 10:11 UTC, hasancelik approved these changes

2022-12-29 12:38 UTC, merged