[CN-585] Add operator chart and update make file
hazelcast/hazelcast-platform-operator pull request #524
Opened 2022-12-28 12:05 UTC by cagric0

## Description

Add operator helm chart 
Add new make commands
Update `tilt` file for using updated make commands
Replace `NAME_PREFIX` with `RELEASE_NAME` in the test workflows
Update workflows for using `generate-crds-yaml` make command
Update `bundle.yaml` using updated `generate-bundle-yaml` make command

## User Impact

2023-01-03 17:48 UTC, cheels commented on CONTRIBUTING.md
> +6.  Before you push, run the command `make lint` in your terminal and fix the linter errors if any. Push your PR once it is free of linter errors.
Nothing about what to do if contributor wants to modify the API of Custom Resourses and how it should be reflected with our new structure (with Helm). Is it ok?

2023-01-03 22:20 UTC, dzeromski-hazelcast approved these changes

2023-01-04 13:26 UTC, hasancelik requested changes

2023-01-04 13:26 UTC, hasancelik commented on helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/Chart.yaml
> +version: 5.0.6-alpha
```suggestion
version: 5.0.6-rc
```

2023-01-04 13:26 UTC, hasancelik commented on helm-charts/hazelcast-platform-operator/Chart.yaml
> +version: 5.0.6-alpha
And also, why are we using `5.0.6`, not `5.6`?

2023-01-09 07:25 UTC, mtyazici commented on Makefile
> +DEPLOYMENT_NAME := $(RELEASE_NAME)-hazelcast-platform-operator
I did not try this case but, DEPLOYMENT_NAME might not work in operators deployed with OLM.

2023-01-09 11:42 UTC, cagric0 commented on Makefile
> +DEPLOYMENT_NAME := $(RELEASE_NAME)-hazelcast-platform-operator
We are using this field only in the test env. In `deployment.yaml` we are still passing POD_NAME

2023-01-09 12:28 UTC, merged