[CN-668] - Add workflow to release operator helm chart
hazelcast/hazelcast-platform-operator pull request #535
Opened 2023-01-02 17:59 UTC by cheels

## Description

Added a new workflow that allows pushing helm chart directly into https://github.com/hazelcast/charts.git based on changes in helm-chart/ folder in current repo

2023-01-03 09:13 UTC, cagric0 requested changes

2023-01-03 09:13 UTC, cagric0 commented on .github/workflows/helm-chart-release.yaml
> +      - 'helm-chart/**'
```suggestion
      - 'helm-charts/**'
```

2023-01-03 09:13 UTC, cagric0 commented on .github/workflows/helm-chart-release.yaml
> +          cp -rf helm-chart/hazelcast-platform-operator/* charts/stable/hazelcast-platform-operator
```suggestion
          cp -rf helm-charts/hazelcast-platform-operator/* charts/stable/hazelcast-platform-operator
```

2023-01-03 09:13 UTC, cagric0 commented on .github/workflows/helm-chart-release.yaml
> +          git commit --signoff -m "${{github.event.head_commit.message}}"
Is this `github.event.head_commit.message` the commit message from operator repo?

2023-01-03 09:53 UTC, cheels commented on .github/workflows/helm-chart-release.yaml
> +          git commit --signoff -m "${{github.event.head_commit.message}}"
Yes, it comes from the operator repo

2023-01-03 09:55 UTC, cagric0 approved these changes
It's not a big deal but it seems the PR name is not proper. Could you update it?

2023-01-03 22:19 UTC, dzeromski-hazelcast approved these changes

2023-01-04 11:36 UTC, cheels commented on .github/workflows/helm-chart-release.yaml
> +name: Helm Chart Release
```suggestion
name: Helm Chart Update
```

2023-01-04 11:37 UTC, merged