[CN-606][CN-607] Introduce highAvailabilityMode is configuration to create clusters are resilient to node and zone failures
hazelcast/hazelcast-platform-operator pull request #538
Opened 2023-01-03 09:51 UTC by hasancelik

Other changes:
- implemented webhook to validate(prevent) highAvailabilityMode update.
- renamed ValidateNotUpdatableFields to ValidateNotUpdatableMapFields which belongs to Map CR webhook.
- implemented integration tests for feature itself and webhook.

## User Impact

Introduce highAvailabilityMode is a configuration to create clusters that are resilient to node and zone failures.

2023-01-05 11:42 UTC, SeriyBg requested changes

2023-01-05 11:42 UTC, SeriyBg commented on api/v1alpha1/hazelcast_types.go
> +	// Configuration to create clusters are resilient to node and zone failures
```suggestion
	// Configuration to create clusters resilient to node and zone failures
```

2023-01-05 11:42 UTC, SeriyBg commented on api/v1alpha1/hazelcast_webhook.go
> +	n "github.com/hazelcast/hazelcast-platform-operator/internal/naming"
Could you please move this import to the block import at the bottom?

2023-01-05 11:42 UTC, SeriyBg commented on controllers/hazelcast/hazelcast_resources.go
> +		case "NODE":
```suggestion
		case hazelcastv1alpha1.HighAvailabilityNodeMode:
```

2023-01-05 11:42 UTC, SeriyBg commented on controllers/hazelcast/hazelcast_resources.go
> +		case "ZONE":
```suggestion
		case hazelcastv1alpha1.HighAvailabilityZoneMode:
```

2023-01-05 12:22 UTC, dzeromski-hazelcast approved these changes

2023-01-05 14:14 UTC, SeriyBg requested changes
Just one more suggestion 😃

2023-01-05 14:14 UTC, SeriyBg commented on test/integration/hazelcast_webhook_test.go
> +			}
```suggestion
			var err error
			for {
				Expect(k8sClient.Get(
					context.Background(), types.NamespacedName{Namespace: hz.Namespace, Name: hz.Name}, hz)).Should(Succeed())
				hz.Spec.HighAvailabilityMode = hazelcastv1alpha1.HighAvailabilityNodeMode
				err = k8sClient.Update(context.Background(), hz)
				if errors.IsConflict(err) {
					continue
				}
				break
			}
			Expect(err).
				Should(MatchError(ContainSubstring("highAvailabilityMode cannot be updated")))
```
I would suggest the following changes that retry the update in case of the conflict; otherwise, in case of the conflict, the test will test nothing.

2023-01-05 19:55 UTC, hasancelik commented on test/integration/hazelcast_webhook_test.go
> +			}
good catch 🤦‍♂️ 😄

2023-01-09 09:32 UTC, SeriyBg approved these changes

2023-01-09 09:51 UTC, merged