[CN-449] add connectivity check to wan replication cr
hazelcast/hazelcast-platform-operator pull request #541
Opened 2023-01-03 18:17 UTC by kutluhanmetin

## Description

- While applying WAN Replication
```
cat <<EOF | kubectl apply -f -
apiVersion: hazelcast.com/v1alpha1
kind: WanReplication
metadata:
  name: example-wan-replication
spec:
  resources:
    - name: hazelcast-first
      kind: Hazelcast
  targetClusterName: dev
  endpoints: "<SECOND-CLUSTER-EXTERNAL-IP>"
EOF
```

The sidecar container inside Hazelcast Pod tries a TCP Connection to the target cluster specified as `SECOND-CLUSTER-EXTERNAL-IP`. 

## User Impact
When creating a WAN Replication CR, user is going to be sure that target cluster is reachable.

2023-01-03 18:23 UTC, kutluhanmetin commented
This is blocked by: https://github.com/hazelcast/hazelcast-platform-operator-agent/pull/40. Before merging this PR, new agent version must be released, and it must be updated in operator with this PR.

2023-01-03 22:33 UTC, dzeromski-hazelcast approved these changes

2023-01-03 22:33 UTC, dzeromski-hazelcast commented on controllers/hazelcast/wanreplication_controller.go
> +	for _, memberAddress := range memberAddresses {
I think we can run test on a random node. No need to check if all of them have access. What do you think?

2023-01-03 22:33 UTC, dzeromski-hazelcast commented on controllers/hazelcast/wanreplication_controller.go
> +		ping, err := p.Ping(ctx, endpoints)
Can we drop `ping` return value? Looks like `ping` and `err` are exclusive. Only one variable is set so we can simplify and just check for `err`?

2023-01-03 22:33 UTC, dzeromski-hazelcast commented on controllers/hazelcast/wanreplication_controller.go
> +	"github.com/hazelcast/hazelcast-platform-operator/internal/mtls"
can we keep stdlib imports separate from our and third-party imports?

2023-01-03 22:33 UTC, dzeromski-hazelcast commented on internal/pinger/pinger.go
> +	"github.com/hazelcast/hazelcast-platform-operator/internal/rest"
Separate stdlib imports? :)

2023-01-03 22:33 UTC, dzeromski-hazelcast commented on internal/rest/pinger_service.go
> +type PingRequest struct {
Can we define `PingRequest` and `PingResponse` in operator-agent and then import it? Just like we do for other services?

2023-01-03 22:33 UTC, dzeromski-hazelcast commented on internal/rest/pinger_service.go
> +	var uploadResp *PingResponse
We define here `*PingResponse` nil pointer. Shouldn't we define normal struct `PingResponse` here and pass pointer to `.Do` methods so that we have a storage for the struct?

2023-01-03 22:33 UTC, dzeromski-hazelcast commented on internal/pinger/pinger.go
> +func NewPinger(config *Config) (*Pinger, error) {
Not sure this is the best name. Could we maybe switch to something like "ConnectivityService" or "Dial". We are not doing icmp pings like the name "Pinger" could imply.

2023-01-04 08:06 UTC, kutluhanmetin commented on controllers/hazelcast/wanreplication_controller.go
> +	for _, memberAddress := range memberAddresses {
I didn't understand the reason actually. Because we have a source cluster and a target cluster. Target cluster should be reachable from all the members of the source cluster I think.

2023-01-04 08:11 UTC, kutluhanmetin commented on internal/rest/pinger_service.go
> +type PingRequest struct {
Well, I think it is a general issue we need to talk about it. Because I didn't release the agent yet, It is also in review. I think we have two options to resolve this problem:
- Monorepo (I strongly suggest adding monorepo codebase to operator repository)
- Break the dependency to agent code like I did in this PR, and keep them sync all the time.

2023-01-04 08:28 UTC, kutluhanmetin commented on controllers/hazelcast/wanreplication_controller.go
> +		ping, err := p.Ping(ctx, endpoints)
Done 👍

2023-01-04 08:28 UTC, kutluhanmetin commented on internal/pinger/pinger.go
> +	"github.com/hazelcast/hazelcast-platform-operator/internal/rest"
Done 👍

2023-01-04 08:28 UTC, kutluhanmetin commented on internal/rest/pinger_service.go
> +	var uploadResp *PingResponse
Done 👍

2023-01-04 08:29 UTC, kutluhanmetin commented on controllers/hazelcast/wanreplication_controller.go
> +	"github.com/hazelcast/hazelcast-platform-operator/internal/mtls"
Done 👍

2023-01-09 07:18 UTC, mtyazici requested changes
Left some comments about the reconciler function :+1:

2023-01-09 07:18 UTC, mtyazici commented on api/v1alpha1/hazelcast_types.go
> +	// +kubebuilder:default:="0.1.14"
We should revert it when we decide to merge the PR.

2023-01-09 07:18 UTC, mtyazici commented on controllers/hazelcast/wanreplication_controller.go
> +	for _, rr := range wan.Spec.Resources {
Should we take this part into a function? Also this logic should be put after the finalizer executor logic since any error in this part can prevent the resource from getting deleted.

2023-01-09 07:28 UTC, kutluhanmetin commented on api/v1alpha1/hazelcast_types.go
> +	// +kubebuilder:default:="0.1.14"
I know 👍

2023-01-09 07:30 UTC, kutluhanmetin commented on internal/rest/pinger_service.go
> +type PingRequest struct {
Added a retro item for this one

2023-01-09 09:12 UTC, mtyazici commented on controllers/hazelcast/wanreplication_controller.go
> +			logger.Error(errors.New("get Hazelcast Status Service failed"), "")
Should we return the error here instead of logging?

2023-01-09 10:37 UTC, kutluhanmetin commented on controllers/hazelcast/wanreplication_controller.go
> +			logger.Error(errors.New("get Hazelcast Status Service failed"), "")
Done.

2023-01-09 11:01 UTC, dzeromski-hazelcast commented on controllers/hazelcast/wanreplication_controller.go
> +	for _, memberAddress := range memberAddresses {
Does replication run on all nodes or just the main node? In addition iterating over all members will be slow for large clusters. If you want to keep it then we should use concurrency here like we do in backup and restore.

2023-01-10 20:18 UTC, kutluhanmetin commented on controllers/hazelcast/wanreplication_controller.go
> +	for _, memberAddress := range memberAddresses {
Added the following commit on agent side to make it concurrent and limit with timeout:
https://github.com/hazelcast/hazelcast-platform-operator-agent/pull/40/commits/4d5de46bf8de16e09bc2baa034b3233470bfca99

2023-01-11 11:06 UTC, mtyazici approved these changes

2023-01-11 18:11 UTC, merged