[CN-693]- Add new feature to README.md and CSV file
hazelcast/hazelcast-platform-operator pull request #576
Opened 2023-01-17 19:33 UTC by cheels

## Description

Update README.md file and CSV files with new features.

2023-01-18 14:10 UTC, hasancelik requested changes

2023-01-18 14:10 UTC, hasancelik commented on README.md
> +* Persistence support for the Cache CR
I think we can remove this line 
```suggestion

```

2023-01-18 16:24 UTC, cheels commented on config/manifests/bases/hazelcast-platform-operator.clusterserviceversion.yaml
> +    * Persistence support for the Cache CR
```suggestion
```

2023-01-18 16:24 UTC, cheels commented on config/manifests/bases/hazelcast-platform-operator.clusterserviceversion.yaml
> +    * Persistence support for the Cache CR
@hasancelik Should I remove it from CSV file as well?

2023-01-23 06:56 UTC, hasancelik commented on config/manifests/bases/hazelcast-platform-operator.clusterserviceversion.yaml
> +    * Persistence support for the Cache CR
I have suggested this change for CSV file actually 🙂

2023-01-24 11:33 UTC, merged