[CN-704] Remove side effects from status update functions
hazelcast/hazelcast-platform-operator pull request #621
Opened 2023-02-09 09:53 UTC by mtyazici

## Description

Status update functions for all CRs were updating all the fields in the status object. Now, update functions only updates explicit fields.

## User Impact

2023-02-17 07:43 UTC, cagric0 commented on controllers/hazelcast/queue_controller.go
> +		withDSMessage("Persisting the applied multiMap config."),
```suggestion
		withDSMessage("Persisting the applied Queue config."),
```

2023-02-17 08:07 UTC, cagric0 requested changes
LGTM!

2023-02-17 08:19 UTC, cagric0 approved these changes

2023-02-20 14:40 UTC, SeriyBg approved these changes

2023-03-07 12:55 UTC, mtyazici commented on controllers/hazelcast/queue_controller.go
> +		withDSMessage("Persisting the applied multiMap config."),
test-comment

2023-03-07 13:01 UTC, cagric0 commented on controllers/hazelcast/queue_controller.go
> +		withDSMessage("Persisting the applied multiMap config."),
requested-comment

2023-03-23 11:43 UTC, merged