Trigger WanReplication with Hazelcast resource when new map is created
hazelcast/hazelcast-platform-operator pull request #656
Opened 2023-03-12 19:57 UTC by semihbkgr

## Description

## User Impact

2023-03-14 12:05 UTC, semihbkgr commented
I am not totally sure about if e2e test is correct way to test this new behaviour comes with this PR.

2023-03-27 08:40 UTC, hasancelik requested changes

2023-03-27 08:40 UTC, hasancelik commented on test/e2e/hazelcast_wan_test.go
> +	//When("Map is given twice in the Wan spec",
```suggestion
	//When("Map is given twice in the WAN spec",
```

I think WAN is more correct usage 🙂

2023-03-27 08:40 UTC, hasancelik commented on controllers/hazelcast/wanreplication_controller.go
> +func (r *WanReplicationReconciler) beingSuccessfulMapUpdates(m client.Object) []reconcile.Request {
```suggestion
func (r *WanReplicationReconciler) findNewlyCreatedMaps(m client.Object) []reconcile.Request {
```
or 
```suggestion
func (r *WanReplicationReconciler) findNewMaps(m client.Object) []reconcile.Request {
```
are better namings, I think

2023-03-27 08:40 UTC, hasancelik commented on controllers/hazelcast/wanreplication_controller.go
> +			builder.WithPredicates(predicate.Funcs{
Why do we need a predicate here? Can we directly watch other resources as we do for terminated maps?

2023-03-27 08:40 UTC, hasancelik commented on controllers/hazelcast/wanreplication_controller.go
> +func (r *WanReplicationReconciler) beingSuccessfulMapUpdates(m client.Object) []reconcile.Request {
`terminatingMapUpdates` is not also good naming; what about `findTerminatedMaps` or `findTerminatationCandidateMaps`? cc: @mtyazici

2023-03-28 09:15 UTC, semihbkgr commented on controllers/hazelcast/wanreplication_controller.go
> +			builder.WithPredicates(predicate.Funcs{
@SeriyBg is right. It is easier way to filter for specific events and their desired conditions. It also let you have more control over the changed resources (be able to access old resource object `updateEvent.ObjectOld` on update).

```go
return oldMap.Status.State != hazelcastv1alpha1.MapSuccess && 
    newMap.Status.State == hazelcastv1alpha1.MapSuccess
```

In this way, we can run handler only when the map status is set to `success` and we don't need to have additional conditional checks in handler logic.

2023-03-28 14:08 UTC, hasancelik commented on controllers/hazelcast/wanreplication_controller.go
> +func (r *WanReplicationReconciler) beingSuccessfulMapUpdates(m client.Object) []reconcile.Request {
sounds good to me 👍

2023-03-28 14:09 UTC, hasancelik commented on controllers/hazelcast/wanreplication_controller.go
> +			builder.WithPredicates(predicate.Funcs{
I see, thanks for the explanation guys ✋

2023-03-30 13:31 UTC, cagric0 requested changes
LGTM! Except one missing if check.

2023-03-30 13:31 UTC, cagric0 commented on controllers/hazelcast/wanreplication_controller.go
> +			}
```suggestion
			case hazelcastv1alpha1.ResourceKindHZ:
				if resource.Name == mp.Spec.HazelcastResourceName {
					reqs = append(reqs, reconcile.Request{
						NamespacedName: types.NamespacedName{
							Name:      wan.Name,
							Namespace: wan.Namespace,
						},
					})
					break
				}
			}
```

2023-03-31 12:32 UTC, hasancelik approved these changes

2023-03-31 13:33 UTC, cagric0 approved these changes

2023-04-05 01:36 UTC, semihbkgr commented
WAN tests are not passing if the Hazelcast CR doesn't have this advanced network configuration. It seems like it is different than default configuration.

```go
hz.Spec.AdvancedNetwork.WAN = []hazelcastcomv1alpha1.WANConfig{
    {
        Port:        5710,
        PortCount:   0,
        ServiceType: "NodePort",
        Name:        "tokyo",
    },
}
```

It is not caused by the changes applied in this PR.

All existing WAN tests are also failing when removing this advanced network configuration: #689
https://github.com/hazelcast/hazelcast-platform-operator/actions/runs/4613886129?pr=689

2023-04-05 01:39 UTC, semihbkgr commented
I think this PR is ready to merge.

> ## Test Results
> Total Tests	🔴 Failures	🟠 Errors	⚪ Skipped
> [OS](https://hazelcast.github.io/hazelcast-platform-operator/pr/2682/#suites/0b301d038a17885b818e60273771cfeb)	78	0	0	40
> [EE](https://hazelcast.github.io/hazelcast-platform-operator/pr/2682/#suites/fb850ba25ceb06c7b2b56dd821744585)	79	1	0	14

The failed tests is flaky Mancenter test btw.

2023-04-05 09:28 UTC, merged