[CN-638]: Add near cache support for Map CR
hazelcast/hazelcast-platform-operator pull request #661
Opened 2023-03-16 10:39 UTC by kutluhanmetin

## Description

Near Cache support for Map CR is added. However, there are some problems with codec and I opened issues for them on core side (continued with default values):
- https://github.com/hazelcast/hazelcast/issues/23978
- https://github.com/hazelcast/hazelcast/issues/23979

## User Impact

User will be able to configure Near Cache for Map CR.
Example:

```
apiVersion: hazelcast.com/v1alpha1
kind: Map
metadata:
  name: mostly-read-map
spec:
  hazelcastResourceName: hazelcast
  nearCache:
      inMemoryFormat: OBJECT
      invalidateOnChange: true
      timeToLiveSeconds: 300
      maxIdleSeconds: 300
      eviction:
        evictionPolicy: NONE
        maxSizePolicy: ENTRY_COUNT
        size: 5000
      cacheLocalEntries: true
```

2023-03-20 11:17 UTC, SeriyBg requested changes
One small comment

2023-03-20 11:17 UTC, SeriyBg commented on test/integration/hazelcast_controller_test.go
> +				Delete(m)
I guess all the cleanup should happen in `After` functions to prevent interference with other tests

2023-03-21 07:20 UTC, kutluhanmetin commented on test/integration/hazelcast_controller_test.go
> +				Delete(m)
Would you give an example from tests? I see similar uses of `Delete(m)` in almost every controller test.

2023-03-21 08:38 UTC, SeriyBg commented on test/integration/hazelcast_controller_test.go
> +				Delete(m)
You are right, but this seems wrong. The correct approach would be to cleanup in the `AfterSuite` as in the E2E tests. However, I think it can be fixed in a separate PR. Could you please create a ticker for this?

2023-03-21 08:39 UTC, SeriyBg approved these changes

2023-03-21 11:29 UTC, kutluhanmetin commented on test/integration/hazelcast_controller_test.go
> +				Delete(m)
okay 👍

2023-03-29 13:43 UTC, merged