Added workflow to test Operator on multiple version
hazelcast/hazelcast-platform-operator pull request #670
Opened 2023-03-20 20:24 UTC by cheels

## Description

- Added workflow to test the latest Operator on multiple latest HZ and MC versions: 5.1.x and 5.0.x.
- As a result, there is one report will be created: 
<img width="795" alt="image" src="https://user-images.githubusercontent.com/8906445/226457283-0f3d28bb-4dce-4e66-a58e-62126e635b52.png">

2023-03-27 06:51 UTC, mtyazici approved these changes

2023-03-27 09:25 UTC, hasancelik requested changes

2023-03-27 09:25 UTC, hasancelik commented on .github/workflows/multi-version-tests.yaml
> +    - cron: "0 9 */3 * *"
Running this build every three days does not make sense. Because we know that this suite will fail with the current latest versions until they release them, we can keep the suite manual trigger based and run it before the releases to see if additional failures exist.

2023-03-28 14:06 UTC, hasancelik approved these changes

2023-03-28 22:31 UTC, merged