[CN-864] Add support for custom configs using ConfigMap
hazelcast/hazelcast-platform-operator pull request #750
Opened 2023-06-05 14:31 UTC by SeriyBg

## User Impact

Added possibility to add custom Hazelcast configuration specified in ConfigMap via `customConfigCmName` field in Hazelcast CR

2023-06-07 10:54 UTC, cagric0 approved these changes
LGTM!

2023-06-08 08:32 UTC, semihbkgr requested changes
What would happen if user gives incorrect Hazelcast config fields in custom config map. Should we check custom config fields in validation?

2023-06-08 08:32 UTC, semihbkgr commented on controllers/hazelcast/hazelcast_resources.go
> +func mergeCustomConfig(cfg *config.Hazelcast, cstCfg map[string]interface{}) error {
This function basically merges the `config` into the `custom config`. Would be good to rename the function and change the parameters order.

2023-06-08 08:32 UTC, semihbkgr commented on test/integration/hazelcast_config_test.go
We did you create a new test file instead of residing them in `hazelcast_test.go`

2023-06-08 08:41 UTC, SeriyBg commented on controllers/hazelcast/hazelcast_resources.go
> +func mergeCustomConfig(cfg *config.Hazelcast, cstCfg map[string]interface{}) error {
Would you happen to have any suggestions for the name?
Why change the order of the parameters?

2023-06-08 08:43 UTC, SeriyBg commented on test/integration/hazelcast_config_test.go
This test file is focused only on the Hazelcast config. I'm not a big fan of having huge files with everything in it, and think that it's better to separate them for a better readbility

2023-06-08 08:44 UTC, SeriyBg commented
> What would happen if user gives incorrect Hazelcast config fields in custom config map. Should we check custom config fields in validation?

The decision on not to validate the custom config. Here you can find the reasoning: https://hazelcast.atlassian.net/wiki/spaces/CN/pages/4513398825/Custom+config+support+for+Hazelcast+CR#Should-we-validate-the-custom-config%3F

2023-06-08 08:46 UTC, semihbkgr commented on controllers/hazelcast/hazelcast_resources.go
> +func mergeCustomConfig(cfg *config.Hazelcast, cstCfg map[string]interface{}) error {
my suggestion: `func mergeConfig(cstCfg map[string]interface{},cfg *config.Hazelcast) error`

2023-06-08 08:49 UTC, semihbkgr approved these changes

2023-06-08 09:34 UTC, semihbkgr approved these changes

2023-06-08 11:41 UTC, merged