[CN-801] Implement JetJobSnapshot CR
hazelcast/hazelcast-platform-operator pull request #751
Opened 2023-06-05 18:47 UTC by semihbkgr

## Description

Implementation of JetJobSnapshot CR

## User Impact

Add JetJobSnapshot CR that provides a way to export snapshots of JetJob CRs.

2023-06-21 12:14 UTC, SeriyBg requested changes

2023-06-21 12:14 UTC, SeriyBg commented on controllers/hazelcast/jetjobsnapshot_controller.go
> +		logger.Info("Exporting process has already been started", "name", jjs.SnapshotName(), "cancelJob", jjs.Spec.CancelJob)
Probably for such log it's better set the debug level

2023-06-21 12:14 UTC, SeriyBg commented on controllers/hazelcast/jetjobsnapshot_controller.go
> +	r.exportingSnapshotMap.Delete(k)
Is it right to delete the entry before the finalizer is deleted?

2023-07-04 20:19 UTC, cagric0 reviewed
Overall LGTM. Thanks for the huge effort you put for making the operator great with the jet job!!! I left some minor comments, after you address them and Sergii's comments. I'll approve it.

2023-07-05 02:59 UTC, semihbkgr commented on controllers/hazelcast/jetjobsnapshot_controller.go
> +	r.exportingSnapshotMap.Delete(k)
Nice catch 👍. I think it isn't right, but we are doing it in multiple CRs finalizer such as Hazelcast CR, JetJob CR. 
We can create a new ticket referring the order of the operations in the finalizers. What do you think?

2023-07-05 03:10 UTC, semihbkgr commented on api/v1alpha1/jetjobsnapshot_validation.go
> +func ValidateJetJobSnapshot(h *Hazelcast) error {
Yes, but since the scope of the functions is package level in Go, so I cannot set so generic name to this function.
I have only conformed the naming convention we have in JetJob validation.

```go
func ValidateJetConfiguration(h *Hazelcast) error {
```

We can find more generic solution or better naming convention for these functions.

2023-07-05 04:59 UTC, semihbkgr commented on api/v1alpha1/jetjobsnapshot_validation.go
> +func ValidateJetJobSnapshot(h *Hazelcast) error {
`ValidateHazelcasEnterprise` would be better 👍

2023-07-05 06:24 UTC, semihbkgr commented
why the new commit are not included in the PR

2023-07-05 07:36 UTC, semihbkgr commented
migrated to #791 as the new incoming commits are not loaded in the PR.

2023-07-05 07:36 UTC, closed without merging

2023-07-05 11:44 UTC, semihbkgr commented on controllers/hazelcast/jetjobsnapshot_controller.go
> +	r.exportingSnapshotMap.Delete(k)
We missed the case where getting an error after deleting finalizer. Just imagine we removed the finalizer first, then get en error while applying actual finalizer operations. Then we cannot stand a chance to run reconciler and finalizer again.

2023-07-05 11:59 UTC, SeriyBg commented on controllers/hazelcast/jetjobsnapshot_controller.go
> +	r.exportingSnapshotMap.Delete(k)
But what if during the finalizer operations an error occurs, but the `exportingSnapshotMap` entry is already deleted?

2023-07-05 12:05 UTC, semihbkgr commented on controllers/hazelcast/jetjobsnapshot_controller.go
> +	r.exportingSnapshotMap.Delete(k)
If that happens, then the reconciler will be triggered again and the finalizer is called again. What is the problem?