[CN-882] Delete JetJob CR when its Hazelcast CR is deleted
hazelcast/hazelcast-platform-operator pull request #771
Opened 2023-06-23 08:22 UTC by semihbkgr

## Description

Finalizer of Hazelcast CR deletes its dependent JetJob CRs. 
When the JetJob CR is deleted, if its Hazelcast CR has marked to be deleted, (we assume that the deletion operation of JetJob CR is triggered by Hazelcast CR finalizer), then the JetJob finalizer does't cancel the actual job. In this way, the jet jobs in the cluster can be recovered by `losslesRestart`.

## User Impact

When Hazelcast CR object is getting deleted, its dependent JetJob CR objects are deleted as well without canceling the actual jobs.

2023-06-23 08:48 UTC, SeriyBg commented on controllers/hazelcast/jetjob_controller.go
> +func (r *JetJobReconciler) stopJetExecution(ctx context.Context, jj *hazelcastv1alpha1.JetJob, h *hazelcastv1alpha1.Hazelcast, logger logr.Logger) error {
It seems that we only need Hazelcast's `types.NamespacedName`, not the entire `hazelcastv1alpha1.Hazelcast` object here

2023-06-26 10:42 UTC, semihbkgr commented on controllers/hazelcast/jetjob_controller.go
> +func (r *JetJobReconciler) stopJetExecution(ctx context.Context, jj *hazelcastv1alpha1.JetJob, h *hazelcastv1alpha1.Hazelcast, logger logr.Logger) error {
That is true and also would be good to have an utility function that returns `types.NamespacedName` of the given resource. We are doing this same thing lots of time in the source code.

2023-06-29 08:06 UTC, SeriyBg requested changes

2023-06-29 08:06 UTC, SeriyBg commented on controllers/hazelcast/jetjob_controller.go
> +			return nil
Don't we need to remove the finalizer and `removeJobFromChecker` in this case?

2023-07-03 08:49 UTC, semihbkgr commented on controllers/hazelcast/jetjob_controller.go
> +			return nil
It is better removing the finalizer when Hazelcast CR is not found 👍

2023-07-03 10:57 UTC, SeriyBg approved these changes

2023-07-04 07:51 UTC, merged