[CN-891] fix mutation detection for CR update
hazelcast/hazelcast-platform-operator pull request #783
Opened 2023-07-03 15:09 UTC by SeriyBg

Update the CRD when mutated in the reconciler

2023-07-03 20:44 UTC, semihbkgr requested changes
It is just small suggestion.

2023-07-03 20:44 UTC, semihbkgr commented on controllers/hazelcast/mutate/mutate.go
> +	if !reflect.DeepEqual(oldHz, &h) {
return statement can be simplified

2023-07-04 07:42 UTC, SeriyBg commented on controllers/hazelcast/mutate/mutate.go
> +	if !reflect.DeepEqual(oldHz, &h) {
`mutated` variable might be changed above. IMO, such simplification will make the code less readable

2023-07-04 07:51 UTC, semihbkgr commented on controllers/hazelcast/mutate/mutate.go
> +	if !reflect.DeepEqual(oldHz, &h) {
I meant something like this
```go
oldHz := &h
h.Default()
if h.Spec.GetLicenseKeySecretName() != "" && h.Spec.Repository == n.HazelcastRepo {
		h.Spec.Repository = n.HazelcastEERepo
		return true
}
return !reflect.DeepEqual(oldHz, &h)
```
not big deal, It is still good anyway 👍

2023-07-04 07:51 UTC, semihbkgr approved these changes
LGTM

2023-07-04 08:38 UTC, hasancelik approved these changes

2023-07-04 08:40 UTC, merged