[DO NOT MERGE] JetJobSnapshot implementation
hazelcast/hazelcast-platform-operator pull request #791
Opened 2023-07-05 06:23 UTC by semihbkgr

## Description

## User Impact

2023-07-05 09:00 UTC, SeriyBg requested changes

2023-07-05 09:00 UTC, SeriyBg commented on api/v1alpha1/cache_types.go
> +	EventJournal *EventJournal `json:"eventJournal,omitempty"`
Is this change related to the JetJobSnapshot? Because if it is not, this change will be missing from the release notes

2023-07-05 09:00 UTC, SeriyBg commented on api/v1alpha1/jetjobsnapshot_validation.go
> +	if jjs.Spec.JetJobResourceName == "" {
The field's `//+required` tag is enough for the validation

2023-07-05 09:00 UTC, SeriyBg commented on controllers/hazelcast/jetjob_controller.go
> +			err := fmt.Errorf("JetJobSnapshot '%s' has not exported", job.Spec.InitialSnapshotResourceName)
```suggestion
			err := fmt.Errorf("JetJobSnapshot '%s' is not exported", job.Spec.InitialSnapshotResourceName)
```

2023-07-05 09:00 UTC, SeriyBg commented on controllers/hazelcast/jetjobsnapshot_controller.go
> +	if hz.Status.Phase != hazelcastv1alpha1.Running {
Isn't this check redundant? We already check for the JetJob state, and it won't be `Running` if the Hazelcast cluster isn't running

2023-07-05 09:30 UTC, semihbkgr commented on api/v1alpha1/cache_types.go
> +	EventJournal *EventJournal `json:"eventJournal,omitempty"`
Should we create task or add in release notes?

2023-07-05 09:36 UTC, semihbkgr commented on api/v1alpha1/jetjobsnapshot_validation.go
> +	if jjs.Spec.JetJobResourceName == "" {
Are you sure?
Without this check, I could have created snapshot with empty `JetJobResourceName`.

2023-07-05 09:41 UTC, SeriyBg commented on api/v1alpha1/jetjobsnapshot_validation.go
> +	if jjs.Spec.JetJobResourceName == "" {
Then you can use `// +kubebuilder:validation:MinLength:=`, this will work for sure

2023-07-05 09:42 UTC, SeriyBg commented on api/v1alpha1/cache_types.go
> +	EventJournal *EventJournal `json:"eventJournal,omitempty"`
We should probably manually add to release notes. If it's already added, then there is no need to remove it, but we have to include in the release notes

2023-07-05 10:00 UTC, cagric0 commented on api/v1alpha1/jetjobsnapshot_validation.go
> +	if jjs.Spec.JetJobResourceName == "" {
I am gonna ask you the same question Semih. Are you sure :) 
It shouldn't be like you said. For example, I tried it for map CR. I tried to create map CR without passing `hazelcastResourceName` and I got the following error.

`error: error validating "map.yaml": error validating data: ValidationError(Map.spec): missing required field "hazelcastResourceName" in com.hazelcast.v1alpha1.Map.spec; if you choose to ignore these errors, turn validation off with --validate=false`

2023-07-05 16:08 UTC, cagric0 approved these changes

2023-07-06 03:33 UTC, semihbkgr commented on api/v1alpha1/cache_types.go
> +	EventJournal *EventJournal `json:"eventJournal,omitempty"`
I have informed Alex about that. We will add EventJournal in RN manually after release 👍

2023-07-06 12:58 UTC, merged