[CN-1106] Fix AKS workflow creating NSG rule to allow external connections
hazelcast/hazelcast-platform-operator pull request #958
Opened 2023-12-29 10:05 UTC by semihbkgr

## Description

Create NetworkSecurityGroup inbound rule to accept external connections to the nodes.

2023-12-30 09:59 UTC, SeriyBg requested changes

2023-12-30 09:59 UTC, SeriyBg commented on .github/workflows/e2e-aks.yaml
> +            NRG=$(cat output.json | jq -r .nodeResourceGroup)
Do we need to create this temporary file? Maybe we can directly use the pipe to `jq`?
```suggestion
            NRG=$(az aks create \
              --resource-group=${AZURE_RESOURCE_GROUP} \
              --name="${CLUSTER_NAME}" \
              --node-count=3 \
              --enable-node-public-ip \
              --generate-ssh-keys | jq -r .nodeResourceGroup)
```

2024-01-04 11:59 UTC, semihbkgr commented on .github/workflows/e2e-aks.yaml
> +            NRG=$(cat output.json | jq -r .nodeResourceGroup)
Yes, we can simply use pipe to extract `nodeResourceGroup` from output of `az aks create` 👍

2024-01-04 13:22 UTC, SeriyBg approved these changes

2024-01-04 14:16 UTC, merged