Add WanSync support [CN-369]
hazelcast/hazelcast-platform-operator pull request #977
Opened 2024-01-17 15:31 UTC by SeriyBg

## User Impact

Add support of full and delta WAN Sync using WanSync CR

2024-01-24 09:52 UTC, hasancelik commented on config/samples/_v1alpha1_wansync.yaml
> +    resources:
leftover?

2024-01-24 09:52 UTC, hasancelik commented on config/samples/_v1alpha1_wansync_test.yaml
> +      - name: map-1
Leftover?

2024-01-25 09:36 UTC, semihbkgr requested changes
We need to add tags of new e2e test-suites (`hz_wan_sync`) into Makefile and utils.sh to trigger them.

https://github.com/hazelcast/hazelcast-platform-operator/blob/main/.github/scripts/utils.sh#L367

https://github.com/hazelcast/hazelcast-platform-operator/blob/main/Makefile#L205

2024-01-25 11:21 UTC, SeriyBg commented
> We need to add tags of new e2e test-suites (`hz_wan_sync`) into Makefile and utils.sh to trigger them.
> 
> https://github.com/hazelcast/hazelcast-platform-operator/blob/main/.github/scripts/utils.sh#L367
> 
> https://github.com/hazelcast/hazelcast-platform-operator/blob/main/Makefile#L205

@semihbkgr I've added it to the Makefile, but why would we need it in the utils.sh?

2024-01-26 12:16 UTC, hasancelik requested changes

2024-01-29 08:47 UTC, SeriyBg commented on api/v1alpha1/wansync_validation.go
> +func (v *wansyncValidator) validateNonUpdatableWanFields(w *WanSync) {
What do you mean by WAN Replication? Here, we are checking the WanSync fields only, which for now is only the WAN Replication name

2024-01-29 09:38 UTC, SeriyBg commented on internal/util/annotation.go
> +}
That was my intension. I have relaced the most obvious places with the usage of function from this file.

2024-01-29 09:45 UTC, hasancelik commented on api/v1alpha1/wansync_validation.go
> +func (v *wansyncValidator) validateNonUpdatableWanFields(w *WanSync) {
I see; I misunderstood the code 🤦‍♂️

2024-01-29 09:46 UTC, hasancelik approved these changes
LGTM! Thanks for the PR @SeriyBg 💯

2024-01-29 10:53 UTC, semihbkgr commented
@SeriyBg 
> I've added it to the Makefile, but why would we need it in the utils.sh?

IIRC, in the test workflows, we are using the test suites declared in utils.sh.

2024-01-29 12:06 UTC, semihbkgr approved these changes
LGTM 👍

2024-01-29 12:06 UTC, semihbkgr commented on controllers/hazelcast/wansync_controller.go
> +func (r *WanSyncReconciler) runWanSyncJobs(ctx context.Context, maps map[string][]hazelcastv1alpha1.Map, wan *hazelcastv1alpha1.WanSync, wr *hazelcastv1alpha1.WanReplication, logger logr.Logger) erro
I get a bit confused with this function. Is it safe against concurrent call of the reconciler to avoid executing wanSync multiple times through codec?

2024-01-29 12:09 UTC, SeriyBg commented on controllers/hazelcast/wansync_controller.go
> +func (r *WanSyncReconciler) runWanSyncJobs(ctx context.Context, maps map[string][]hazelcastv1alpha1.Map, wan *hazelcastv1alpha1.WanSync, wr *hazelcastv1alpha1.WanReplication, logger logr.Logger) erro
Reconciler by default does not run concurrently

2024-01-30 16:19 UTC, SeriyBg commented on internal/util/annotation.go
> +func InsertLastSuccessfullyAppliedSpec(spec interface{}, obj client.Object) client.Object {
Well, we can. But we still have this package, and the idea is that this funcs can be used for both `hazelcast` and `mamangementcenter` packages

2024-01-30 16:28 UTC, SeriyBg commented on internal/hazelcast-client/wan_sync_service.go
> +type HzWanSyncService struct {
Well, it was an interface, and that's why it has the `Hz` prefix. Then, I refactored it and forgot to remove the prefix. Will remove it

2024-01-31 07:51 UTC, SeriyBg commented on internal/util/annotation.go
> +func InsertLastSuccessfullyAppliedSpec(spec interface{}, obj client.Object) client.Object {
Move it to `controller` package, as the initial suggestion

2024-01-31 10:02 UTC, cheels commented on config/samples/_v1alpha1_wansync.yaml
> +  wanReplicationName: wan-replication-sample
Here should be **wanReplicationResourceName** instead of **wanReplicationName**

2024-01-31 10:09 UTC, cheels commented on helm-charts/hazelcast-platform-operator/charts/hazelcast-platform-operator-crds/templates/all-crds.yaml
> +              wanReplicationResourceName:
When you apply WanSync CR without **spec. wanReplicationResourceName** the validation is missing and it applied 
successfully. 

For example:

apiVersion: hazelcast.com/v1alpha1
kind: WanSync
metadata:
  name: wan-sync-sample

2024-01-31 14:10 UTC, cheels approved these changes

2024-02-01 10:19 UTC, merged