[CN-1083] Add resources field to agent container
hazelcast/hazelcast-platform-operator pull request #980
Opened 2024-01-24 19:17 UTC by kutluhanmetin

## Description

Fixes https://github.com/hazelcast/hazelcast-platform-operator/issues/927

## User Impact

Users will be able to configure resources field for agent.

Example:

```
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  ...
  agent: 
    repository: hazelcast/platform-operator-agent
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```

2024-01-25 08:22 UTC, cagric0 requested changes
Just a minor comment word change. Just a reminder, the comments are used as description for the fields so you'll need to regenerate crd definitions.

2024-01-25 08:22 UTC, cagric0 commented on api/v1alpha1/hazelcast_types.go
> +	// Compute Resources required by the Hazelcast container.
```suggestion
	// Compute Resources required by the Agent container.
```

2024-01-25 08:38 UTC, SeriyBg approved these changes

2024-01-30 09:18 UTC, cagric0 approved these changes

2024-01-30 09:20 UTC, merged